### PR TITLE
fix(firebase_messaging): Ensure correct `sentTime` date is passed with `RemoteMessage` on iOS.

### PR DESCRIPTION
**Pull request by russellwheatley**
## Description

See title. 

Xcode console log of correct value sent as double in milliseconds since epoch (1970)  from iOS side:

Screenshot 2021-12-16 at 10 42 39

## Related Issues

fixes https://github.com/FirebaseExtended/flutterfire/issues/7434

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Salakar** [comment]
I'm not sure this is the right fix here, the original issue indicates to me that we need to take `sentTime` on iOS and multiply it by 1000 to convert it from _seconds_ to _milliseconds_, since the assumption in Dart is that it is in _milliseconds_: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_message.dart#L48 - and iOS is sending it in _seconds_ since epoch, hence the date showing incorrectly on the issue as a few days after the epoch date (January 1st, 1970) since it's adding _seconds_ as _milliseconds_ incorrectly.

Here is where I would convert the seconds to milliseconds; https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m#L793 - should be a one liner fix.

(also; `response.notification.date` is the time the notification was displayed on the device and is an iOS API, not the time it was sent on FCM)

**Review by Salakar — CHANGES_REQUESTED** [review]
See previous comment

**Comment by russellwheatley** [comment]
> I'm not sure this is the right fix here, the original issue indicates to me that we need to take `sentTime` on iOS and multiply it by 1000 to convert it from _seconds_ to _milliseconds_, since the assumption in Dart is that it is in _milliseconds_: [`master`/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_message.dart#L48](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_message.dart?rgh-link-date=2021-12-16T13%3A49%3A49Z#L48) - and iOS is sending it in _seconds_ since epoch, hence the date showing incorrectly on the issue as a few days after the epoch date (January 1st, 1970) since it's adding _seconds_ as _milliseconds_ incorrectly.
> 
> Here is where I would convert the seconds to milliseconds; 

>[`master`/packages/firebase_messaging/firebase_messaging/ios/Classes/>FLTFirebaseMessagingPlugin.m#L793](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m?rgh-link-date=2021-12-16T13%3A49%3A49Z#L793) - should be a one liner fix.

> (also; `response.notification.date` is the time the notification was displayed on the device and is an iOS API, not the time it was sent on FCM)

The property `google.c.a.ts` doesn't come through for any of the events. At least not on iOS 14 which is the version on my iPhone.
Screenshot 2021-12-16 at 19 13 41

**Comment by russellwheatley** [comment]
There's an open issue on the [firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk/issues/9151) for the `sentTime` & `from`  properties that are missing when receiving messages via Firebase Messaging iOS SDK.

**Pull request closed without merging**
