### PR TITLE
feat(firebase_remote_config)!: migrate to nullsafety

### PR DESCRIPTION
**Pull request by daniloadorno**
Replacement for #5397

### CODE REVIEW

**Comment by Zeswen** [comment]
Looking forward to it :)

**Comment by rrousselGit** [comment]
@googlebot I consent.

**Comment by TheJulianJES** [comment]
Getting the following error:
```
flutter: Null check operator used on a null value
flutter: #0      convertPlatformException (package:firebase_remote_config_platform_interface/src/method_channel/utils/exception.dart:9:5)
#1      MethodChannelFirebaseRemoteConfig.fetchAndActivate (package:firebase_remote_config_platform_interface/src/method_channel/method_channel_firebase_remote_config.dart:155:13)
<asynchronous suspension>
#2      RemoteConfig.fetchAndActivate (package:firebase_remote_config/src/remote_config.dart:86:26)
<asynchronous suspension>
#3      ConfigService.refreshRemoteConfig (package:glplanflutter/service/config_service.dart:47:7)
<asynchronous suspension>
#4      ConfigService.startRefresh (package:glplanflutter/service/config_service.dart:30:5)
<asynchronous suspension>
flutter: Unable to fetch remote config
```

**Comment by b-jan** [comment]
Hello, is it ready? Can you merge it?

**Review by Duc56789 — APPROVED** [review]

**Comment by rrousselGit** [comment]
We have some failing tests that needs to be fixed

**Comment by b-jan** [comment]
@rrousselGit How much time do you need? Can I help?

**Comment by russellwheatley** [comment]
@googlebot I consent.

**Comment by Zeswen** [comment]
@rrousselGit waiting for your review!

Everyone nice work with the update, thank you so much for your contributions!

**Review by Salakar — APPROVED** [review]

**Review by rrousselGit — APPROVED** [review]

**Comment by Zeswen** [comment]
Are you going to make the release today? Or are you waiting on other fixes?

**Comment by TheJulianJES** [comment]
You can always use something like this:

```
dependencies:
  # ...
  firebase_remote_config:
    git:
      url: git://github.com/FirebaseExtended/flutterfire
      ref: master
      path: packages/firebase_remote_config/firebase_remote_config
```

```
dependency_overrides:
  firebase_remote_config_platform_interface:
    git:
      url: git://github.com/FirebaseExtended/flutterfire
      ref: master
      path: packages/firebase_remote_config/firebase_remote_config_platform_interface
```

**Comment by Salakar** [comment]
This has now been published to pub.dev as `0.10.0-dev.0` - thanks everyone.

**Comment by albertolina** [comment]
> Getting the following error:
> 
> ```
> flutter: Null check operator used on a null value
> flutter: #0      convertPlatformException (package:firebase_remote_config_platform_interface/src/method_channel/utils/exception.dart:9:5)
> #1      MethodChannelFirebaseRemoteConfig.fetchAndActivate (package:firebase_remote_config_platform_interface/src/method_channel/method_channel_firebase_remote_config.dart:155:13)
> <asynchronous suspension>
> #2      RemoteConfig.fetchAndActivate (package:firebase_remote_config/src/remote_config.dart:86:26)
> <asynchronous suspension>
> ```
> 
> Edit: Same reason for the build failing: https://github.com/FirebaseExtended/flutterfire/pull/5686/checks?check_run_id=2288832143#step:6:265

Hello, I am getting the same error when I try to initialise remote config. Any solutions?

The error appears when I run:
`    final RemoteConfig remoteConfig = await RemoteConfig.instance;
    final defaults = <String, dynamic>{'welcome': 'default welcome'};
    await remoteConfig.setDefaults(defaults);`

Thank you!

**Comment by Salakar** [comment]
@albertolina would you mind creating a new GitHub issue for your problem and add some more detail to it there and tag myself (@Salakar) and @rrousselGit in it - thanks.

**Pull request merged**
