### PR TITLE
docs(cloud_functions): update emulator usage instructions

### PR DESCRIPTION
**Pull request by MaxAuer**
## Description

The instructions on how to use the emulator for functions were not in line with emulator usages from other packages (Auth, Firestore).

Also, the example code would not work if one needed to use the callable's return value.

This makes the instructions more clear and easier to follow.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by rrousselGit** [comment]
> Also, the example code would not work if one needed to use the callable's return value.

I don't quite understand. What does this mean?

**Comment by MaxAuer** [comment]
To make it more clear:

```dart
FirebaseFunctions.instance
  .useFunctionsEmulator(origin: 'http://localhost:5000')
  .httpsCallable('myCloudFunction');
```

Chaining `.httpsCallable('myCloudFunction')` after `.useFunctionsEmulator(...)` does result in the compiler issuing a [use_of_void_result](https://dart.dev/tools/diagnostic-messages#use_of_void_result).

The code will not compile. 

Also the example code do makes the impression that `.useFunctionsEmulator(...)` is needed on every `.httpsCallable(...)` call. Which is not the case. 

A simple 
```dart
FirebaseFunctions.instance.useFunctionsEmulator(origin: 'http://localhost:5000');
```
at the start of the application is enough.

**Review by rrousselGit — APPROVED** [review]
Oh, fair enough

**Review by stark090909 — COMMENTED** [review]
No

**Pull request merged**
