### PR TITLE
fix(firebase_auth): Revert #4312: Double event fire on initialization

### PR DESCRIPTION
**Pull request by Sese-Schneider**
## Description

This PR reverts https://github.com/FirebaseExtended/flutterfire/pull/4312 .

**Reason:**
The old PR aimed to surpress a secondary event fired on app reload / hot reload or sometimes on initialization.

However, on page reload (browser, not hot restart) only a `null` _initialization(?)_ event gets fired - not a secondary event containing the correct user login change.
The secondary user event gets surpressed by the changes the PR made.

This should be merged as a double event with correct data is better than only a single faulty event.
The issue with the double event has to be adressed otherwise.

I don't know why this has been merged in the first place 🤔 

**Steps to reproduce:**
- Create an app with an `authStateChanges` listener which loggs the current user.
- Login a user.
- Reload the Browser

_Behaviour_:
- `master`: `null`
- this revert: `null` -> user

> Why this is beneficial: The **double event** is fired **reliably** instead of only one or two events in some cases.

## Related Issues

- https://github.com/FirebaseExtended/flutterfire/pull/4312

**This PR reopens:**
- https://github.com/FirebaseExtended/flutterfire/issues/3591
- https://github.com/FirebaseExtended/flutterfire/issues/3356

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

/cc @creativecreatorormaybenot 

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
I think it might be worth opening a new issue for this, so the FirebaseExtended team recognizes this **regression** 👌 

cc @russellwheatley

**Comment by creativecreatorormaybenot** [comment]
@Salakar I would have liked to comment on the original issue (https://github.com/FirebaseExtended/flutterfire/issues/3591) or the PR (https://github.com/FirebaseExtended/flutterfire/pull/4312), however, these conversations are locked - why is that?

**Comment by Salakar** [comment]
> I don't know why this has been merged in the first place

As it was an issue that needed fixing. Also hard to test things correctly between reloads on e2e testing (though something we're looking at improving).

> however, these conversations are locked - why is that?

This is the google bot locking them automatically after a few days when closed, we have no control over it sorry. I have pinged a Googler and asked to turn it off or increase the time.

----

I'm ok with reverting this

**Review by Salakar — APPROVED** [review]

**Comment by Salakar** [comment]
Reverted & published.

**Pull request merged**
