### PR TITLE
[firebase_messaging] fixed platform dependency error

### PR DESCRIPTION
**Pull request by preetjdp**
## Description

This PR solves the package `firebase_messaging` from working `flutter 1.22.0-2.0.pre.36`, the problem was related to the package `platform`, the solution was to remove the package.

## Related Issues

* https://github.com/FirebaseExtended/flutterfire/issues/3312

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by preetjdp** [comment]
@googlebot I signed it!

**Comment by acoutts** [comment]
Looking forward to this 👍  had to downgrade from Dev to Beta channel.

**Comment by acoutts** [comment]
@preetjdp I think the conflicting change in pubspec is due to the recent commit here where they fixed up the local example include paths. I think if you merge from the latest master here it will fix it up.

**Comment by preetjdp** [comment]
@acoutts The actual fix is just a one-line tweak to remove this dependency 
https://github.com/FirebaseExtended/flutterfire/blob/7eb9e21f82a09c5cecebfc231b256545cf1ce073/packages/firebase_messaging/pubspec.yaml#L18

I'm sure @Salakar is aware of this and thus blocked the merge of the PR.

**Comment by Salakar** [comment]
I blocked this one as it's incomplete, analyzer is failing as theres some usages of the 'platform' dependency still being used in the code that also need replacing. Was going to reply but slipped my mind sorry 😅

**Comment by Salakar** [comment]
This has been resolved on master. Thanks for the PR.

**Pull request closed without merging**
