### PR TITLE
[firebase_admob] feat: support adaptive banner for admob

### PR DESCRIPTION
**Pull request by uny**
## Description

Support admob adaptive banner.
https://developers.google.com/admob/ios/banner/adaptive
https://developers.google.com/admob/android/banner/adaptive

## Related Issues

https://github.com/FirebaseExtended/flutterfire/issues/2003

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by marciorr** [comment]
It would be very nice to have adaptive banners. Any idea when it will be available?

**Comment by peterweb2005** [comment]
better have an example on how to apply the "quickstart"

https://developers.google.com/admob/android/banner/adaptive#quickstart

**Comment by ycv005** [comment]
@amirh @bparrishMines please have a look at this pr by @uny .

**Comment by ycv005** [comment]
@uny WIll you tell, how to use it. I have copied your code but unable to figure out how to use it or start with it. Thanks in advance.

**Comment by bparrishMines** [comment]
@uny @ycv005 Our team is unable to look at this as we are currently focused on adding widget support for Ads and have started a closed beta: https://medium.com/flutter/new-ads-beta-inline-banner-and-native-support-for-the-flutter-mobile-ads-plugin-e48a7e9a0e64.

Feel free to follow https://github.com/flutter/flutter/issues/12114. The work on the new Ads plugin will most likely lead to deprecating this one, so we are focusing on getting it to open beta where everyone can use the new plugin.

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.

**Pull request closed without merging**
