### PR TITLE
fix(firebase_auth): authentication forceResendingToken int can be null on iOS

### PR DESCRIPTION
**Pull request by JYeop**
## Description

When using firebase auth package - phone authentication with ios device, the error occurs below.
```
Unhandled Exception: type 'Null' is not a subtype of type 'int'
#0      MethodChannelFirebaseAuth.verifyPhoneNumber.
```
So I changed below
```dart
// method_channel_firebase_auth.dart
else if (name == 'Auth#phoneCodeSent') {
          final String verificationId = arguments['verificationId'];
          final int forceResendingToken = arguments['forceResendingToken'];
```
to
```dart
// method_channel_firebase_auth.dart
else if (name == 'Auth#phoneCodeSent') {
          final String verificationId = arguments['verificationId'];
          final int? forceResendingToken = arguments['forceResendingToken'];
```

This PR solves the type error that ios devices could not sign in with phone.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by lastthyme — APPROVED** [review]

**Comment by nzackoya** [comment]
Seriously? When are you going to release this?

**Review by nzackoya — APPROVED** [review]
`forceResendingToken` shouldn't be null at all, but this is anyway a hot fix allowing the developer to catch and hide code resending at least instead of just crashing

**Comment by nzackoya** [comment]
@JYeop please fix the title of the PR
`Run amannn/action-semantic-pull-request@v1.2.0
4
Error: No release type found in pull request title " authentication phoneCodeSent int cannot be null error".
5

6
Add a prefix like "fix: ", "feat: " or "feat!: " to indicate what kind of release this pull request corresponds to. The title should match the commit mesage format as specified by https://www.conventionalcommits.org/.`

**Comment by DhavalRKansara** [comment]
I am facing the same issue

**Comment by arunkpatra** [comment]
I am blocked in this issue too

**Comment by ened** [comment]
@nzackoya `forceResendingToken` is not available on iOS, so definitely can be null here I think. The PR addresses this correctly.

**Comment by ened** [comment]
@Salakar, @rrousselGit Can confirm this bug as well. This may have gotten lost during the integration test stage during the event channel work. The fix in #5944 should fix it.

The issue will not be present on non-nullsafe projects (flutter create xxx) and appear immediately after `dart migrate`.

**Comment by DhavalRKansara** [comment]
@rrousselGit Is there anyone working on it? Do you guys have any release plan or we have to downgrade our projects from non-nul safety.

**Comment by ened** [comment]
@DhavalRKansara you can refer to this PR in your project like so:

``` yaml
dependency_overrides:
  firebase_messaging:
    git:
      url: https://github.com/JYeop/flutterfire
      path: packages/firebase_messaging
      ref: c39cdb28f21d290f4a72df9829d37468c87a5bc8
```

That should help to get your project compile until the PR is reviewed, tested, merged..

**Comment by JYeop** [comment]
Anyone who has tested can approve this PR.
*Fixed the title to pass the cla, Sorry!

**Review by Salakar — APPROVED** [review]

**Comment by DhavalRKansara** [comment]
> @DhavalRKansara you can refer to this PR in your project like so:
> 
> ```yaml
> dependency_overrides:
>   firebase_messaging:
>     git:
>       url: https://github.com/JYeop/flutterfire
>       path: packages/firebase_messaging
>       ref: c39cdb28f21d290f4a72df9829d37468c87a5bc8
> ```
> 
> That should help to get your project compile until the PR is reviewed, tested, merged..

As I can see the PR is merged.... is this merge PR is released?

**Pull request merged**
