### PR TITLE
feat: Add withConverter function to CollectionReference, DocumentReference and Query

### PR DESCRIPTION
**Pull request by rrousselGit**
## Description

`withConverter` transforms a reference to manipulate a custom object instead
 of a `Map<String, dynamic>`.

 This makes both read and write operations type-safe.

 ```dart
 final usersRef = FirebaseFirestore
     .instance
     .collection('users')
     .withConverter<User>(
       fromFirestore: (snapshot, _) => User.fromJson(snapshot.data()!),
       toFirestore: (user, _) => user.toJson(),
     );

 Future<void> main() async {
   // Writes now take a User as parameter instead of a Map
   await usersRef.add(User(name: 'John'));

   // Reads now return a User instead of a Map
   final User user = await usersRef.doc('123').get().then((s) => s.data());
 }
 ```

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Salakar** [comment]
Shall we have a dedicated documentation page for this? Is there a specific third party library we can couple inside a complete documentation example/tutorial, e.g. `json_serializable`?

**Review by Salakar — APPROVED** [review]

**Comment by Nolence** [comment]
This is so cool ! I'm really liking it so far :D

This might not be a common use case but I have one collection that is just composed of document Ids. That is, the documents are empty and I only use this list to index into other collections.

I was wondering how or if the `withConverter` could handle this situation -- converting to a List<String> for just document IDs. Something like have a second parameter (or a class with the values as fields) to hold the document reference/document id.

```dart
final freeQuestionIdsRef = _instance
    .collection('free_question_ids')
    .withConverter<String>(
      fromFirebase: (json, reference) => reference.id,
      // This might instead return a value key kind of thing where both might be optional ??? spitballing
      toFirebase: (String questionID) => MyMapEntry(key: questionID),
    );
```

I also imagine people will somehow want to attach their document reference to their model in some way so they can easily update that reference. I'd imagine someone just slapping them together in a tuple:

```dart
final usersRef = _instance
    .collection(_profiles)
    .withConverter<Tuple2<DocumentReference, Profile>>(
      fromFirebase: (json, reference) =>
          Tuple2(reference, Profile.fromJson(json)),
      toFirebase: (tupleData) => tupleData.item2.toJson(),
    );
```

Which of course would be further simplified when/if tuple native support lands. Also, would there be no way to make DocumentReference generic so its `get` and `set` might be typesafe as well?

Despite these suggestions, this is an awesome PR. Very much looking forward to it

**Comment by rrousselGit** [comment]
> I was wondering how or if the `withConverter` could handle this situation

You should be able to do:

```dart
final freeQuestionIdsRef = _instance
    .collection('free_question_ids')
    .withConverter<String>(
      fromFirestore: (DocumentSnapshot snapshot, _) => snapshot.id,
      toFirestore: (String id, _) => const {},
    );
```

although I'm not sure that's really valuable

> Also, would there be no way to make DocumentReference generic so its get and set might be typesafe as well?

That would be a breaking change, as existing code would see their `get` called return `dynamic` instead of `Map<String, dynamic>` like it currently does.

It's possible (and preferable), but we try to avoid breaking changes

**Comment by Nolence** [comment]
> although I'm not sure that's really valuable

I can see that, especially as it adds an extra an extra two parameters users will have to consider. I'll leave to maintainers' discretion. Just wanted to point out a possible use case. Thanks !

**Comment by Nolence** [comment]
I imagine a lot of people will want to pass along their `WithConverterDocumentSnapshot<T>` down the widget tree so they can use the the snapshot to update the data `T`. I personally found myself creating a typedef just to shorten the name as its quite long

```dart
typedef DocSnap<T> = WithConverterQueryDocumentSnapshot<T>;
```

```dart
class Article {
  final String title;

  Article({required this.title});
}

class ArticleList extends StatelessWidget {
  final List<WithConverterQueryDocumentSnapshot<Article>> articleSnapshots;

  // Or
  final List<DocSnap<Article>> articleSnapshots;

  ArticleList(this.articleSnapshots);

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemCount: articleSnapshots.length,
      itemBuilder: (context, index) {
        final articleSnapshot = articleSnapshots[index];
        final article = articleSnapshot.data();

        return ListTile(
          title: Text(article.title),
          onTap: () {
            // Clear title
            articleSnapshot.reference.set(article.copyWith(title: ''));
          },
        );
      },
    );
  }
}
```

However typedefs for classes I think is only for sdk >=2.13.0. Not really offering any solution, just an observation I noticed

**Review by Salakar — APPROVED** [review]

**Pull request merged**
