### PR TITLE
[firebase_ml_vision] Add rawBytes to the Barcode class (#1816)

### PR DESCRIPTION
**Pull request by marcus-bornman**
## Description

* Upgrade of the `firebase-ml-vision` android dependancy to `24.0.1` to allow access to [`getRawBytes`](https://firebase.google.com/docs/reference/android/com/google/firebase/ml/vision/barcode/FirebaseVisionBarcode.html#getRawBytes()).
* In the example, upgraded the `firebase-ml-vision-image-label-model` and `firebase-ml-vision-face-model` android dependencies to `19.0.0` to accommodate  the aforementioned upgrade of firebase-ml-vision (Without these upgrades version solving will fail).
* Added `rawBytes` to the `Barcode` class. Populated this with [`getRawBytes`](https://firebase.google.com/docs/reference/android/com/google/firebase/ml/vision/barcode/FirebaseVisionBarcode.html#getRawBytes()) for android and with [`rawData`](https://firebase.google.com/docs/reference/ios/firebasemlvision/api/reference/Classes/FIRVisionBarcode#/c:objc(cs)FIRVisionBarcode(py)rawData) for iOS

## Related Issues

* [[firebase_ml_vision] Add rawBytes to the Barcode class #1816](https://github.com/FirebaseExtended/flutterfire/issues/1816)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by marcus-bornman** [comment]
> @googlebot I fixed it.

**Comment by collinjackson** [comment]
It's a bit unfortunate that we have to release this as a breaking change. If we landed https://github.com/FirebaseExtended/flutterfire/pull/39 then we wouldn't have to make this a breaking change.

**Comment by marcus-bornman** [comment]
> Thanks for the PR! Can we get a unit test for this? See https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_ml_vision/test/firebase_ml_vision_test.dart

Updated the PR by adding `rawBytes` to some existing unit tests - I believe this will suffice?:)

**Comment by marcus-bornman** [comment]
> It's a bit unfortunate that we have to release this as a breaking change. If we landed #39 then we wouldn't have to make this a breaking change.

Definitely unfortunate. Will keep an eye on #39 and update this PR accordingly if it lands 💯

**Comment by marcus-bornman** [comment]
Solved the merge conflicts

**Pull request closed without merging**
