### PR TITLE
docs: add unit test libraries to the list of plugins

### PR DESCRIPTION
**Pull request by atn832**
## Description

Add the following unit test libraries to the list of plugins:
- [cloud_firestore_mocks](https://pub.dev/packages/cloud_firestore_mocks)
- [firebase_auth_mocks](https://pub.dev/packages/firebase_auth_mocks)
- [firebase_storage_mocks](https://pub.dev/packages/firebase_storage_mocks)

## Related Issues

As per https://github.com/FirebaseExtended/flutterfire/discussions/5550#discussioncomment-557644, I am adding documentation about the unit testing libraries onto the website.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by atn832** [comment]
The Deploy Preview workflow fails because it is missing a service account key:

> Error: Input required and not supplied: firebaseServiceAccount

Is there something I should set up for the workflow to run correctly? Seems like the Secret should be set up on FirebaseExtended, not on my fork.

https://github.com/FirebaseExtended/flutterfire/blob/7dc598e7c6e1c3e9df628b40ef3876be33b4aeda/.github/workflows/docs_preview.yaml#L25

**Review by dudss37 — COMMENTED** [review]
- [ ]

**Comment by atn832** [comment]
> * [ ]

What does it mean?

**Review by Duc56789 — COMMENTED** [review]
// Spam comment, removed.

**Review by Duc56789 — COMMENTED** [review]
// Spam comment, removed.

**Comment by rrousselGit** [comment]
@Salakar Is this what you expected when suggesting a PR?

**Comment by atn832** [comment]
> @Salakar Is this what you expected when suggesting a PR?

I can also add a page dedicated to unit testing, something like [this](http://blog.wafrat.com/how-to-write-unit-tests-for-firebase-in-flutter/), which I wrote long ago. I'd prefer making a separate PR for it though.

**Comment by Salakar** [comment]
> > @Salakar Is this what you expected when suggesting a PR?
> 
> I can also add a page dedicated to unit testing, something like [this](http://blog.wafrat.com/how-to-write-unit-tests-for-firebase-in-flutter/), which I wrote long ago. I'd prefer making a separate PR for it though.

A page like this is more what I had in mind vs adding to the table of links, I'd like to keep these packages specific to FlutterFire ones only if possible

**Comment by atn832** [comment]
Alright! Closing this PR and opening #5912 instead.

**Pull request closed without merging**
