### PR TITLE
fix(*): operator `==` takes `Object` parameter

### LINKED ISSUE #5288: 🐛 [cloud_firestore] 'Object.==' and Mockito
I am trying to mock flutter fire plugin using Mockito, however generation fails because of using 'Object.==' inside many flutter fire classes. I reported it to Mockito plugin, however they doubt you should be using it.

Any input from your end ?

https://github.com/dart-lang/mockito/issues/354

### PR DESCRIPTION
**Pull request by mockturtl**
## Description

Replace `operator ==(dynamic other)` with `operator ==(Object other)` everywhere.

If this seems reasonable, I'll follow up on the checklist.

## Related Issues

Fixes #5288

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by mockturtl** [comment]
See commit log https://github.com/FirebaseExtended/flutterfire/pull/5443/commits/015ede52a29cfee132d165168d2648c2e0075ad9 regarding the analyzer error in CI.

**Comment by rrousselGit** [comment]
Looks reasonable, thanks!

The PR is marked as draft, is there anything else you want to add?

**Comment by mockturtl** [comment]
> The PR is marked as draft, is there anything else you want to add?

It should be good to go, thanks!

**Comment by rrousselGit** [comment]
@googlebot I consent.

**Review by Salakar — APPROVED** [review]
LGTM

**Comment by rrousselGit** [comment]
Thanks!

**Pull request merged**
