### PR TITLE
feat: lower iOS & macOS deployment targets for relevant plugins

### PR DESCRIPTION
**Pull request by russellwheatley**
## Description

Replacement PR for https://github.com/FirebaseExtended/flutterfire/pull/4626

Following deployment targets in the `podspec` files for each plugin within the [firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk).

Please note `dynamic_links`, `analytics`, `in_app_messaging` & `performance` did not have an `osx` deployment target within their `podspec` file. So it is assumed, like the other plugins, they target a minimum version of `10.12`.

## Related Issues

closes https://github.com/FirebaseExtended/flutterfire/issues/6204

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by russellwheatley** [comment]
Closing in favour of this PR: https://github.com/FirebaseExtended/flutterfire/pull/6757

**Comment by westy92** [comment]
https://github.com/firebase/firebase-ios-sdk/releases/tag/8.5.0 🎉

**Review by Salakar — CHANGES_REQUESTED** [review]
macos podspecs need updating too, e.g.: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_app_check/firebase_app_check/macos/firebase_app_check.podspec#L49

**Review by Salakar — APPROVED** [review]
LGTM!

LGTM GIF

**Pull request merged**
