### PR TITLE
fix: cannot store null values in firestore on the web

### PR DESCRIPTION
**Pull request by blaueeiner**
## Description

With the introduction of null safety you are not being able to store nested null values in Firestore on the web anymore.

Not working before this fix:

```dart
 await FirebaseFirestore.instance.collection("collection").doc("test").update(<String, dynamic>{
     'test': {
         'nestedKey': null  // <--- causes 
     },
});
```
Exception:

`Expected a value of type 'Object', but got one of type 'Null'`

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by russellwheatley** [comment]
Tested before and after changes, it works as described. I can't see any problem with the code itself. LGTM.

**Review by russellwheatley — APPROVED** [review]

**Comment by rrousselGit** [comment]
We'll need a test for this, to avoid further regressions. I'll write one

**Comment by blaueeiner** [comment]
> We'll need a test for this, to avoid further regressions. I'll write one

@rrousselGit All right thank you. 

I would like to get all the checks pass but to be honest I do not get why remote config is failing here while building for iOS. There shouldn't be anything related with my changes I belief.

**Comment by rrousselGit** [comment]
@googlebot I consent.

**Comment by rrousselGit** [comment]
Looking good, thanks!

**Pull request merged**
