### PR TITLE
fix: update Android `logEvent` to support `parameters` of type `List<Map<String, dynamic>>` to match iOS

### LINKED ISSUE #1036: [firebase_analytics] handle nested json in event params
Calling [`logEvent`](https://github.com/flutter/plugins/blob/master/packages/firebase_analytics/lib/firebase_analytics.dart#L43) with parameters throws unless the map values are [primitives](https://github.com/flutter/plugins/blob/master/packages/firebase_analytics/android/src/main/java/io/flutter/plugins/firebaseanalytics/FirebaseAnalyticsPlugin.java#L154
) and non-null.

It should accept arbitrary JSON and flatten the map for me.

The guardrails around reserved event names are nice.  It would be nice to have more, say, [Error 5 = too many keys](https://firebase.google.com/docs/analytics/errors).

### LINKED ISSUE #2835: [firebase_analytics] List type paramters
Firebase Analytics documents says that "ITEMS" parameter supports "Parcelable[]" for android and "NSArray" for IOS but this feature is missing in Flutter firebase_analytics 5.0.15 and we can't pass List to ITEMS parameter.

Documents for Android:
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event#ADD_TO_CART

Documents for IOS:
https://firebase.google.com/docs/reference/swift/firebaseanalytics/api/reference/Constants#/c:FIREventNames.h@kFIREventAddToCart

### PR DESCRIPTION
**Pull request by tp**
## Description

The `logEvent` params on Android so far only support primitive values (numbers, Strings, boolean).

This change adapts the Java implementation to also support sending `List`s with `Map<String, dynamic>` from the Flutter side.

This worked for us already on iOS, so we just needed this adaptation for Android to reach feature parity.

- Fixes #1036
- Fixes #2835

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by tp** [comment]
Still have to add tests for this PR.

Just wanted to post this early, so I could get some feedback if anyone sees any issue with this approach. Works fine for us in production.

**Comment by tp** [comment]
@googlebot I signed it!

**Comment by tp** [comment]
> My PR includes unit or integration tests for all changed/updated/fixed behaviors

Sadly there wasn't a test of the Java implementation so far, and I don't know yet how to best add one. Any pointers would be appreciated.

**Comment by tp** [comment]
Not sure what happened to `build-ipas+drive-examples`. As this didn't change anything on iOS it should pass just like on master before.

**Comment by tp** [comment]
@collinjackson Can you have a look here please if what we're doing is OK?

We've been running in production with this and it's working fine for us, not the lists are available via Google Tag Manager just like on iOS.

**Comment by alfietham** [comment]
I ran into this exact need, was about to create a PR but glad to find there's already one open!

Any ideas what else might be holding this up @tp ? Any pointers @kroikie ? Happy to help where I can

Btw, I've cloned this fork and rebased onto today's `upstream/master` and checked the diffs. Only conflicts to address are versioning-related in the `CHANGELOG.md` and `pubspec.yaml`'s version number

**Comment by GursheeshSingh** [comment]
Would this throw any Value too long error?

I tried using the custom event with string and it throws an error for lists too long.

**Comment by tp** [comment]
Updated to the latest release version.

Now there is "only" an issue with iOS builds, but that also affects other PRs here and seems unrelated to my changes.

@collinjackson @kroikie Could you help our here moving this forward?

**Review by Salakar — APPROVED** [review]

**Comment by Salakar** [comment]
Closing this in favour of #4394 which is slightly further along in the review process and has tests. Thanks for sending this up though.

**Pull request closed without merging**
