### PR TITLE
fix(firestore): normalize Firestore pointer path

### PR DESCRIPTION
**Pull request by IchordeDionysos**
## Description

Equality checking of references is not user input safe as the internal `Pointer` check unnormalized paths. 

## Related Issues

#2928

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] NOT NEEDED: I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] NOT NEEDED: I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Ehesp** [comment]
Thanks for that, really good catch!

**Comment by IchordeDionysos** [comment]
Not sure if I should update the CHANGELOG or version as a version wasn't yet uploaded?

**Comment by Ehesp** [comment]
Should be ok (cc @Salakar) - we haven't cut a dev release yet and it's not a user facing change so should be good.

**Comment by Salakar** [comment]
> Not sure if I should update the CHANGELOG or version as a version wasn't yet uploaded?

Ye as above, no need to worry about those, though if the behaviour was also incorrect on the previous Firestore before the rework then feel free to add it to the existing change log for the rework.

**Comment by IchordeDionysos** [comment]
@Salakar well, tested it on an older version, and it didn't work there either.

So I'll add it to the CHANGELOG. :)

**Comment by IchordeDionysos** [comment]
**Additional note:**

With the implementation in the PR calling `.path` now always returns the path in the same format, which might be breaking for some users.

But I think is more in line with how the native libraries handle it. :)

```dart
print(Firestore.instance.collection('test').path);
print(Firestore.instance.collection('/test').path);

final snap = await Firestore.instance.document('/some/doc').get();
final ref = snap.data['referenceToOtherDoc'] as DocumentReference;
print(ref.path);
```

Printed originally:
```
test
/test
some/otherDoc
```

And now prints:
```
test
test
some/otherDoc
```

**Web implementation:**
I've checked how web handles it:

```js
console.log(firebase.firestore().collection('test').path);
console.log(firebase.firestore().collection('/test').path);
```

prints out:

```
test
test
```

So I think we should be fine with the implementation of this PR.

**Comment by IchordeDionysos** [comment]
@Salakar After doing some research of the current behavior I think there should definitely some entry in the CHANGELOG, as this 
1. fixes the current behavior for equality checks and 
2. might be a breaking change for some users if they do something like:

```dart
Firestore.instance.collection('/test').path == '/test'
```

**Pull request merged**
