### PR TITLE
[firebase_auth_web] WIP mapping package:firebase FirebaseError to PlatformException

### PR DESCRIPTION
**Pull request by GregorySech**
## Description

I'm mapping the known firebasejs errors (received in package:firebase) to Platform exception as described in https://github.com/FirebaseExtended/flutterfire/issues/1559.

It's still a work in progress, I'll try to add some tests and update documentation when I've got some free time.

## Related Issues

* Closes https://github.com/FirebaseExtended/flutterfire/issues/1559
## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by chen-yumin** [comment]
Could you resolve the merge conflicts please?

**Comment by GregorySech** [comment]
> Thanks for the PR. Could you resolve the merge conflicts please?

This saturday afternoon I'll solve the conflicts.

**Comment by illia-romanenko** [comment]
Hi @GregorySech, will you be able to take a look at this and solve the conflicts?

**Comment by GregorySech** [comment]
> Hi @GregorySech, thanks for your PR! Will you be able to take a look at this and solve the conflicts?

Done, sorry for the delay.

**Comment by flowhorn** [comment]
This PR is really helpful, as before we could'nt receive any error outputs. What is missing to be merged?

**Comment by GregorySech** [comment]
I'm waiting review after solving the merge conflicts.

**Comment by AndroidNils** [comment]
Any updates?

**Comment by GregorySech** [comment]
I will not work with Flutter for a while, I've re-resolved the conflicts. Can this please be reviewed?

**Comment by AndroidNils** [comment]
Thanks for your work! Maybe you can remove `WIP` from the title, if this PR is ready for review 👍

**Comment by GregorySech** [comment]
The related issue was closed and I no longer work with Flutter. Sorry for the time wasted. 
If someone needs me to do something to pass this PR to someone else let me know but I'm closing it.

**Pull request closed without merging**
