### PR TITLE
Contributing file: Fix outdated url

### PR DESCRIPTION
**Pull request by kevmoo**
## Description

Small URL fix for contributing file

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by ditman — APPROVED** [review]
Thanks for updating the URL!

**Comment by ditman** [comment]
I'm going to merge this because the new URL is more correct, but I think this repo is mostly using `melos` now, right? It might be a thing to consider documenting in the CONTRIBUTING.md file @Ehesp!

**Comment by kevmoo** [comment]
`melos`?

**Comment by ditman** [comment]
> Melos is a tool that optimizes the workflow around managing multi-package repositories with git and Pub.

@kevmoo https://github.com/invertase/melos

**Comment by kevmoo** [comment]
So it's like https://github.com/google/mono_repo.dart/

**Pull request merged**
