### PR TITLE
chore(firebase_core): bump core versions

### PR DESCRIPTION
**Pull request by kroikie**
## Description

Version bump in preparation for publishing the updated `firebase_core` plugin. This will be a "pre release" version of the core plugin. Bumping to `v0.5.0-dev.1`. `firebase_core_web` and `firebase_core_platform_interface` are also bumped in a similar way.

### CODE REVIEW

**Comment by Salakar** [comment]
LGTM though wondering if firebase_core_platform_interface should be 2.0.0 as its not currently a 0.x.x release like the others

**Comment by kroikie** [comment]
Agreed, done.

**Comment by awazgyawali** [comment]
When can we expect these new changes to hit pre on pub.dev? There are couple of my PR completely broken due to new tests and version mismatch.

**Comment by Salakar** [comment]
@awazgyawali we're going to get this live on Monday along with Firestore

**Pull request merged**
