### PR TITLE
[firebase_auth] Add a constructor for token result object with a token

### PR DESCRIPTION
**Pull request by mehmetf**
We have applications that implement FirebaseUser class. In order to support this use case, classes such as IdTokenResult need to be open to being constructed as opposed to having only an internal API.

Fixes https://github.com/FirebaseExtended/flutterfire/issues/5

### CODE REVIEW

**Comment by mehmetf** [comment]
Yes, I will write a test for this.

**Comment by mehmetf** [comment]
Done, please take another look.

**Comment by mehmetf** [comment]
Indeed, that's a better solution.

A test would not be required in that case, I would presume since you can always implement any extra classes that get introduced. Would you agree?

**Comment by collinjackson** [comment]
> Indeed, that's a better solution.
> 
> A test would not be required in that case, I would presume since you can always implement any extra classes that get introduced. Would you agree?

Yes, I agree.

**Comment by mehmetf** [comment]
Closing this PR; nothing to see here :-)

**Pull request closed without merging**
