### PR TITLE
[firebase_remote_config]: handle client and server exceptions when fetching remote config

### PR DESCRIPTION
**Pull request by surenyonjan**
## Description

*Currently, we are handling only Throttle Exception when fetching remote config. Firebase Remote Config also provides Server Exception and Client Exception which can help on debugging the problem.*

## Related Issues

*This PR is very much related https://github.com/FirebaseExtended/flutterfire/issues/1572 . We are facing no problem on fetching remote in Development but receiving too many exceptions on Production Environment. Having this change will help to debug exceptions more easily.*

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by surenyonjan** [comment]
@googlebot I signed it!

**Comment by surenyonjan** [comment]
Corrected reference Issue

**Comment by creativecreatorormaybenot** [comment]
Does this not need an implementation on iOS?

Additionally, this should probably be a minor bump rather than a patch, i.e. `0.3.1` because additional functionality is added.

**Comment by surenyonjan** [comment]
> Does this not need an implementation on iOS?
> 
> Additionally, this should probably be a minor bump rather than a patch, i.e. `0.3.1` because additional functionality is added.

Current Firebase Objective C SDK does not have any API for Server/Client Exception as in Android SDK.

Also changed version to `0.3.1`. Please review

**Comment by surenyonjan** [comment]
@creativecreatorormaybenot @helielson Any update on this?

**Comment by creativecreatorormaybenot** [comment]
I am not part of the team and I do not think @helielson is either. In that case, I am not sure why they left a review.

**Comment by Salakar** [comment]
Remote Config has since had a full rework since this PR was created so it's quite far behind and unmergable in it's current state. I can see the latest version does handle `FirebaseRemoteConfigClientException ` https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_remote_config/firebase_remote_config/android/src/main/java/io/flutter/plugins/firebase/firebaseremoteconfig/FirebaseRemoteConfigPlugin.java#L175 but the server one is missing, If you're willing and this is still required please could you send up a new PR for this (apologies this one got stale but it was out of our control).

**Pull request closed without merging**
