### PR TITLE
chore: cherry-pick various commits from NNBD for stable

### PR DESCRIPTION
**Pull request by Salakar**
## Description

Cherry pick a bug fix for Firestore and a feature release for Auth onto the non-null-safety/stable release branch.

## Related Issues

#3565 
#4263

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by dackers86** [comment]
@googlebot I consent.

**Comment by mikehardy** [comment]
@googlebot I consent

**Comment by mikehardy** [comment]
This is fully tangential but I noticed you've still got a separate "cancel workflow runs" action here https://github.com/FirebaseExtended/flutterfire/runs/1823207554 - like react-native-firebase used to have, which requires hard coding workflow IDs etc., but the cancel workflow action was extended some months (almost a year?) back so that you could put it *in* the workflow that should be cancelled, and it will auto-magically get the id for that workflow and cancel it, so you can avoid the separate step, and avoid magical workflow IDs in CI.

**Comment by mikehardy** [comment]
Here is the actionable commit that could be ported: https://github.com/invertase/react-native-firebase/pull/4117/commits/0c357728504ea7e5f90092224c126f2ab818d932

**Pull request merged**
