### PR TITLE
[cloud_firestore] Fixes crash on Android when run a transaction

### LINKED ISSUE #79: [cloud_firestore] Crash app when run transaction on Android device and have no internet connection
* Device: Xiaomi Redmi 7A - Android 9 (API 28)
* Code:
```dart
Future<Map<String, String>> runTransaction(...) {
      final TransactionHandler transactionHandler = (transaction) async {
      final roomRef = _firestore.document('motelrooms/$roomId');
      final documentSnapshot = await transaction.get(roomRef);
      final userIdsSaved = documentSnapshot['user_ids_saved'] as Map;
      final title = documentSnapshot['title'] as String;

      if (userIdsSaved.containsKey(userId)) {
        await transaction.update(
          roomRef,
          <String, dynamic>{
            'user_ids_saved.$userId': FieldValue.delete(),
          },
        );

        return <String, String>{
          'id': documentSnapshot.documentID,
          'title': title,
          'status': 'removed',
        };
      } else {
        await transaction.update(
          roomRef,
          <String, dynamic>{
            'user_ids_saved.$userId': FieldValue.serverTimestamp(),
          },
        );

        return <String, String>{
          'id': documentSnapshot.documentID,
          'title': title,
          'status': 'added',
        };
      }
    };

    return _firestore.runTransaction(transactionHandler, timeout: timeout).then(
        (result) => result is Map<String, String>
            ? result
            : result.cast<String, String>());
}
```
* Log:
```
E/CloudFirestorePlugin(13024): java.lang.Exception: DoTransaction failed: UNAVAILABLE: Unable to resolve host firestore.googleapis.com
E/CloudFirestorePlugin(13024): java.util.concurrent.ExecutionException: java.lang.Exception: DoTransaction failed: UNAVAILABLE: Unable to resolve host firestore.googleapis.com
E/CloudFirestorePlugin(13024): 	at com.google.android.gms.tasks.Tasks.zzb(Unknown Source:61)
E/CloudFirestorePlugin(13024): 	at com.google.android.gms.tasks.Tasks.await(Unknown Source:33)
E/CloudFirestorePlugin(13024): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:424)
E/CloudFirestorePlugin(13024): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:376)
E/CloudFirestorePlugin(13024): 	at com.google.firebase.firestore.FirebaseFirestore.lambda$runTransaction$1(com.google.firebase:firebase-firestore@@19.0.0:283)
E/CloudFirestorePlugin(13024): 	at com.google.firebase.firestore.FirebaseFirestore$$Lambda$3.call(Unknown Source:6)
E/CloudFirestorePlugin(13024): 	at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
E/CloudFirestorePlugin(13024): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/CloudFirestorePlugin(13024): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/CloudFirestorePlugin(13024): 	at java.lang.Thread.run(Thread.java:764)
E/CloudFirestorePlugin(13024): Caused by: java.lang.Exception: DoTransaction failed: UNAVAILABLE: Unable to resolve host firestore.googleapis.com
E/CloudFirestorePlugin(13024): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4$1$1.error(CloudFirestorePlugin.java:406)
E/CloudFirestorePlugin(13024): 	at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:201)
E/CloudFirestorePlugin(13024): 	at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:114)
E/CloudFirestorePlugin(13024): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:653)
E/CloudFirestorePlugin(13024): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/CloudFirestorePlugin(13024): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/CloudFirestorePlugin(13024): 	at android.os.Looper.loop(Looper.java:165)
E/CloudFirestorePlugin(13024): 	at android.app.ActivityThread.main(ActivityThread.java:6861)
E/CloudFirestorePlugin(13024): 	at java.lang.reflect.Method.invoke(Native Method)
E/CloudFirestorePlugin(13024): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/CloudFirestorePlugin(13024): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
D/AndroidRuntime(13024): Shutting down VM
E/AndroidRuntime(13024): FATAL EXCEPTION: main
E/AndroidRuntime(13024): Process: com.hoc.findroom, PID: 13024
E/AndroidRuntime(13024): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(13024): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:135)
E/AndroidRuntime(13024): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/AndroidRuntime(13024): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$3.onComplete(CloudFirestorePlugin.java:442)
E/AndroidRuntime(13024): 	at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
E/AndroidRuntime(13024): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(13024): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(13024): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(13024): 	at android.app.ActivityThread.main(ActivityThread.java:6861)
E/AndroidRuntime(13024): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13024): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(13024): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
I/Process (13024): Sending signal. PID: 13024 SIG: 9
Lost connection to device.
```
 When run on iOS device, `runTransaction(...)` method return a `Future` that completes with an error.

### PR DESCRIPTION
**Pull request by hoc081098**
## Description

* Fixes crash on Android when run a transaction and without internet connection.
* This occurred because:

`Tasks.await(transactionTCSTask, timeout, TimeUnit.MILLISECONDS)`
throws a `Exception`
→ `result.error("Error performing transaction", e.getMessage(), null)` will be called
→ transaction result is `null`
→ in `addOnCompleteListener`#`onComplete`:
```java
    if (task.isSuccessful()) { // result is null
      result.success(task.getResult());
    }
```
will also be called
→ **result#success has been called after result#error**
→ This cause `java.lang.IllegalStateException: Reply already submitted`

## Related Issues

fix #79 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by hoc081098** [comment]
@googlebot I signed it!

**Comment by hoc081098** [comment]
Nice working

**Comment by creativecreatorormaybenot** [comment]
Wow. Thanks so much for this PR. I was seeing this crash for quite a while now. In Crashlytics it shows as the following:

### DartMessenger.java line 35
#### io.flutter.embedding.engine.dart.DartMessenger$Reply.reply 

This PR will resolve #102.  
It was just now that I figured out why this was happening as well. Lucky that I saw this PR before finishing my implementation - saving me some work. This shows that it really is benificial to create an issue with a PR or include a stack trace or similar in the PR (or issue) description so that it becomes searchable. I searched for the crash, but could not find anything.

**Comment by creativecreatorormaybenot** [comment]
@collinjackson Is there a reason this is not being merged?

**Comment by Tolik7** [comment]
Guys, do you have any progress?! 
I have used  cloud_firestore: 0.12.9+4 and I get crash of my app due 'offline' transaction every time!
When it can be retested again? thanks.

**Comment by hoc081098** [comment]
Just waiting 👍

**Comment by jorgercg** [comment]
> Guys, do you have any progress?!
> I have used cloud_firestore: 0.12.9+4 and I get crash of my app due 'offline' transaction every time!
> When it can be retested again? thanks.

Just as a reminder, you can always use it like that:
`cloud_firestore:
    git:
      url: https://github.com/FirebaseExtended/flutterfire.git
      path: packages/cloud_firestore
      ref: 2e7c183`

**Comment by Tolik7** [comment]
Fixed, thanks guys!

**Comment by bpaul7101** [comment]
I still get this crashing. Only on **Android** - LIVE devices and also simulators.

Basically occurs when I try and run a transaction when the device is **offline**

Crashalytics

CloudFirestorePlugin.java line 644
### Caused by java.lang.AssertionError: INTERNAL ASSERTION FAILED: **A transaction object cannot be used after its update callback has been invoked.**
       at com.google.firebase.firestore.util.Assert.fail(com.google.firebase:firebase-firestore@@21.4.0:46)
       at com.google.firebase.firestore.util.Assert.hardAssert(com.google.firebase:firebase-firestore@@21.4.0:31)
       at com.google.firebase.firestore.core.Transaction.ensureCommitNotCalled(com.google.firebase:firebase-firestore@@21.4.0:246)
       at com.google.firebase.firestore.core.Transaction.write(com.google.firebase:firebase-firestore@@21.4.0:241)
       at com.google.firebase.firestore.core.Transaction.set(com.google.firebase:firebase-firestore@@21.4.0:106)
       at com.google.firebase.firestore.Transaction.set(com.google.firebase:firebase-firestore@@21.4.0:91)
       at com.google.firebase.firestore.Transaction.set(com.google.firebase:firebase-firestore@@21.4.0:67)
       at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$7.doInBackground(CloudFirestorePlugin.java:644)
       at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$7.doInBackground(CloudFirestorePlugin.java:638)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
my android/app/build.gradle (Snapshot)

> 
> dependencies {
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'androidx.test:runner :1.1.1'
>     androidTestImplementation 'androidx.test.espresso:espresso-core: 3.1.1'
>     implementation 'com.google.firebase:firebase-analytics: 17.2.2'  
>     implementation 'com.google.firebase:firebase-firestore: 21.4.0'  
>     implementation 'com.google.firebase:firebase-crashlytics: 17.0.0-beta01' 
>  }
> 

Pubspec (Relevant plugins)

> cloud_firestore: 0.13.3 
> cloud_functions: 0.4.1+5 
> google_sign_in: 4.1.4
> firebase_auth: 0.15.2
> firebase_storage: 3.0.11
> 

Flutter doctor

> 
> [✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.3 19D76, locale en-SG)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
> [✓] Android Studio (version 3.5)
> [✓] IntelliJ IDEA Community Edition (version 2018.2.3)
> [✓] VS Code (version 1.42.1)
> [✓] Connected device (11 available)

**Comment by fenchai23** [comment]
Same here:

`E/CloudFirestorePlugin(10092): java.lang.Exception: DoTransaction failed: UNAVAILABLE: Unable to resolve host firestore.googleapis.com
E/CloudFirestorePlugin(10092): java.util.concurrent.ExecutionException: java.lang.Exception: DoTransaction failed: UNAVAILABLE: Unable to resolve host firestore.googleapis.com
E/CloudFirestorePlugin(10092): 	at com.google.android.gms.tasks.Tasks.zzb(Unknown Source:61)
E/CloudFirestorePlugin(10092): 	at com.google.android.gms.tasks.Tasks.await(Unknown Source:33)
E/CloudFirestorePlugin(10092): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:527)
E/CloudFirestorePlugin(10092): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:479)
E/CloudFirestorePlugin(10092): 	at com.google.firebase.firestore.FirebaseFirestore.lambda$runTransaction$0(com.google.firebase:firebase-firestore@@21.3.0:301)
E/CloudFirestorePlugin(10092): 	at com.google.firebase.firestore.FirebaseFirestore$$Lambda$5.call(Unknown Source:6)
`

**Comment by larssn** [comment]
@fenchai23 Transactions are supposed to fail when offline; as it appears that your device was.

**Pull request merged**
