### PR TITLE
docs(ml_vision): add discontinuation message and list alternatives

### PR DESCRIPTION
**Pull request by Salakar**
## Description

ML Kit Vision APIs in Firebase are completely going away in the next iOS and Android SDK releases. This PR adds a discontinued blurb in the readme. I've already marked the package on pub.dev as discontinued; https://pub.dev/packages/firebase_ml_vision 

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Salakar** [comment]
cc @mikehardy - FYI for wording on ML Vision - note that Vision now completely gone from the latest SDKs and the official docs now show using the Cloud APIs via Functions, e.g. https://firebase.google.com/docs/ml/ios/recognize-text

**Review by dackers86 — APPROVED** [review]

**Comment by cngeru** [comment]
What if I'm using the package in production. Will the app be affected. Coz the suggested `google_ml_kit` package doesn't event support `ios`

**Comment by michaellee8** [comment]
> What if I'm using the package in production. Will the app be affected. Coz the suggested `google_ml_kit` package doesn't even support `ios`.

I am also concerned about this. WIll Google offically provide a google_ml_kit flutter plugin that we can use directly? The suggested alternative is not official and lacks iOS support which makes it not the most viable alternative here.

**Comment by AlexHartford** [comment]
Wow. This is really disappointing. 

> The suggested alternative is not official and lacks iOS support which makes it not the most viable alternative here.

It does look like iOS support is being actively worked on in google_ml_kit. While it's not official, it will likely gain a lot of traction / picked up as a flutter favorite, etc. as it advances.

**Pull request merged**
