### PR TITLE
fix: updated firebase dependency to 9.0.0 - Fix for Dio 4.0.0-beta4 dependency collision

### PR DESCRIPTION
**Pull request by dancamdev**
## Description

I've update the firebase dependency of the `firebase_analytics_web` package to 9.0.0, so it would fix a collision if facing with Dio 4.0.0-beta4 and possibly other ones too.

The collision is caused due to a different `http_parser` version `firebase 7.3.0` was using.

The following is the pub get stack trace this PR aims to solve:

```
Because dio >=4.0.0-beta1 depends on http_parser ^4.0.0 and firebase >=7.0.0 <9.0.0 depends on http_parser ^3.0.0, dio >=4.0.0-beta1 is incompatible with firebase >=7.0.0 <9.0.0.

And because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, dio >=4.0.0-beta1 is incompatible with firebase_analytics >=7.1.0.
```

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by dancamdev** [comment]
@googlebot I signed it!

**Comment by Salakar** [comment]
Hey @dancamdev :)

Thanks for this PR, however it has been superseded by #5276 so I won't be able to merge this sorry 🙈

**Comment by dancamdev** [comment]
> Hey @dancamdev :)
> 
> 
> 
> Thanks for this PR, however it has been superseded by #5276 so I won't be able to merge this sorry 🙈 

Awesome! Glad it was fixed already 🙌 is the new version already available?

**Comment by Salakar** [comment]
> > Hey @dancamdev :)
> > Thanks for this PR, however it has been superseded by #5276 so I won't be able to merge this sorry 🙈
> 
> Awesome! Glad it was fixed already 🙌 is the new version already available?

Am publishing right now

**Pull request closed without merging**
