### PR TITLE
fix(dynamic_links): not working on app start (#100)

### PR DESCRIPTION
**Pull request by jherencia**
## Description

People have posted some issues:
- #100 
- #33 
on iOS dynamic links behavior. All of this use cases worked before iOS 12 release so I assume Firebase update and iOS 12 have changed things.

I've based my work on the release of rn-firebase 6.0 that had the same problems and were fixed so this PR takes some ideas from them.

## Related Issues

- #100 
- #33 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by HofmannZ** [comment]
Tested locally, can confirm this solves #100.

**Comment by quetool** [comment]
@jherencia I can confirm your PR fix the problem on iOS when app is in "killed state". Thanks!

**Comment by quetool** [comment]
I dont know why but I needed to add a delay of 700ms in order to get `deepLink.queryParameters`

```
final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.getInitialLink();
final Uri deepLink = data?.link;

if (deepLink != null) {
  Future.delayed(Duration(milliseconds: 700), () {
    print(deepLink.queryParameters)
  });
}

FirebaseDynamicLinks.instance.onLink(onSuccess: (PendingDynamicLinkData dynamicLink) async {
  final Uri deepLink = dynamicLink?.link;

  if (deepLink != null) {
    Future.delayed(Duration(milliseconds: 700), () {
      print(deepLink.queryParameters)
    });
  }
}, onError: (OnLinkErrorException e) async {
  print('onLinkError ' + e.toString());
});
```

**Comment by jherencia** [comment]
> I dont know why but I needed to add a delay of 700ms in order to get `deepLink.queryParameters`
> 
> ```
> final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.getInitialLink();
> final Uri deepLink = data?.link;
> 
> if (deepLink != null) {
>   Future.delayed(Duration(milliseconds: 700), () {
>     print(deepLink.queryParameters)
>   });
> }
> 
> FirebaseDynamicLinks.instance.onLink(onSuccess: (PendingDynamicLinkData dynamicLink) async {
>   final Uri deepLink = dynamicLink?.link;
> 
>   if (deepLink != null) {
>     Future.delayed(Duration(milliseconds: 700), () {
>       print(deepLink.queryParameters)
>     });
>   }
> }, onError: (OnLinkErrorException e) async {
>   print('onLinkError ' + e.toString());
> });
> ```

I'm going to check this.

**Comment by jherencia** [comment]
@quetool 

I've tried and everything work OK without the delay, this is my demo app:

```
import 'package:flutter/material.dart';
import 'package:firebase_dynamic_links/firebase_dynamic_links.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  GlobalKey<ScaffoldState> scaffoldKey = new GlobalKey<ScaffoldState>();

  @override
  void initState() {
    super.initState();
    this.initDynamicLinks();
  }

  void showMessage(String message, { Color backgroundColor = Colors.green}) {
    this.scaffoldKey.currentState.showSnackBar(SnackBar(
      backgroundColor: backgroundColor,
      content: Text(message)
    ));
  }

  void initDynamicLinks() async {
    final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri deepLink = data?.link;

    if (deepLink != null) {
      this.showMessage('onInitialLink: $deepLink');
    }

    FirebaseDynamicLinks.instance.onLink(
      onSuccess: (PendingDynamicLinkData dynamicLink) async {
        final Uri deepLink = dynamicLink?.link;

        if (deepLink != null) {
          this.showMessage('onLinkSuccess $deepLink');
        }
        else {
          this.showMessage('onLinkSuccess empty deepLink', backgroundColor: Colors.orange);
        }
      },
      onError: (OnLinkErrorException e) async {
        this.showMessage('onLinkError ${e.message}', backgroundColor: Colors.red);
      }
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: scaffoldKey,
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'This is an examle of dynamic links, open a dynamic link and you will see the snackBar showing the link',
            ),
          ],
        ),
      ),
    );
  }
}
```

Can you check with this code?

**Comment by quetool** [comment]
@jherencia yes, sorry! I was making a mistake on my code! Everything is working fine without the delay! Thanks!

**Comment by quetool** [comment]
@jherencia is it possible your PR is not working on iOS when a user install the app from a dynamic link? I can't get anything from `FirebaseDynamicLinks.instance.getInitialLink()`

**Comment by JayM96** [comment]
@quetool can you please give me how you have implement your dynamic links in flutter app the thread [Here](https://github.com/FirebaseExtended/flutterfire/issues/1289)

I am stuck. Your help will make my day.

Thanks.

**Comment by logemann** [comment]
fighting with dynamicLinks too. how can i test this fix ? Still on latest dev branch.

**Comment by JayM96** [comment]
I understand. Thanks for your reply.

Still if you can hint if anything I might be doing wrong?

Also, I am using flutter firebase dynamic links plugin. Should I need to integrate your package in my app Or plugin will work properly.

Thanks again.

**Comment by quetool** [comment]
> @quetool can you please give me how you have implement your dynamic links in flutter app the thread [Here](https://github.com/FirebaseExtended/flutterfire/issues/1289)
> 
> I am stuck. Your help will make my day.
> 
> Thanks.

Hi! My this help you? https://github.com/FirebaseExtended/flutterfire/issues/100#issuecomment-541204778
Otherwise, can you describe your issue?

**Comment by HofmannZ** [comment]
@bparrishMines Any thoughts?

**Comment by HofmannZ** [comment]
@collinjackson I have to use this fork for too long now, can we at least get a review?

**Comment by jherencia** [comment]
I've syncronized again the fork and changed the tag so it is independent from the package version which is inconsistent.

```
  firebase_dynamic_links:
    git:
      url: https://github.com/mrmilu/flutterfire.git
      path: packages/firebase_dynamic_links
      ref: PR-255-v1
```

**Comment by kwent** [comment]
How can we help to move this PR forwards. Been few months... Regards

**Comment by jackforesightmobile** [comment]
We're also really interested in getting this PR merged.

**Comment by MrAlek** [comment]
We're also stuck on this. Another ping to maintainers @bparrishMines @collinjackson

**Comment by tapizquent** [comment]
Any update on this??

**Comment by koskimas** [comment]
This is pretty critical for many apps. Without this, there's no way to get the link that opened the app on iOS. Doesn't this bug partially defeat the whole purpose of this library?

**Comment by tapizquent** [comment]
> This is pretty critical for many apps. Without this, there's no way to get the link that opened the app on iOS. Doesn't this bug partially defeat the whole purpose of this library? I'd love to see this merged soon too!

I had to fork this library and implement the fixes myself. Which kinda sucks, as I will have to be paying attention to any breaking changes and re implement the fix.

**Comment by m-j-g** [comment]
> > This is pretty critical for many apps. Without this, there's no way to get the link that opened the app on iOS. Doesn't this bug partially defeat the whole purpose of this library? I'd love to see this merged soon too!
> 
> I had to fork this library and implement the fixes myself. Which kinda sucks, as I will have to be paying attention to any breaking changes and re implement the fix.

Yeah, at this point it is getting pretty ridiculous how inefficient this is being run.

**Comment by HofmannZ** [comment]
Another month has passed, been using a fork for 9 months now, this is absurd... I understand that is open source so time and resources are limited, but this PR has the fix for 9 months now... Just merge already.

**Comment by theneshofficial** [comment]
Please merge it, not sure what’s holding back since all tests are passed.

**Comment by long1eu** [comment]
Why is this not pushed?

**Comment by jherencia** [comment]
Hi all, 

I see movement here and in #100 asking why is this not merged.

It's been a year since I created the PR and we do not know what are the plans of Google about this.

I understand that the codebase has changed significantly in this time so the PR probably need some work. I can work on this if we have a clear path to get this committed.

@bparrishMines @collinjackson can someone give us some light?

**Comment by Salakar** [comment]
@jherencia - FlutterFire maintainer here, and oddly enough the author of the RNFirebase v6 release 😆 

Would love to have this merged to fix this issues - would you be able to update it, or if possible for better visibility send a new PR (and close this one) and tag me in it?

**Comment by jherencia** [comment]
> @jherencia - FlutterFire maintainer here, and oddly enough the author of the RNFirebase v6 release 😆
> 
> Would love to have this merged to fix these issues - would you be able to update it, or if possible for better visibility send a new PR (and close this one) and tag me in it - I can then get it merged and shipped ASAP.

Hi @Salakar,

Ok, I've created a new PR as you suggested:
https://github.com/FirebaseExtended/flutterfire/pull/4354

**Pull request closed without merging**
