### PR TITLE
feat: Full support of AGP 8

### LINKED ISSUE #11266: 🐛 Firebase packages don't fully support AGP 8
## 🐛 Bug report

While trying to upload our app to AGP 8, we were getting error logs like this:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':firebase_analytics'.
> defaultConfig contains custom BuildConfig fields, but the feature is disabled.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 914ms
```
The following code snippet fixed the issue for us when building locally. In each plugin's `android/build.gradle` file, you have to add:
```gradle
android {
    buildFeatures {
        buildConfig = true
    }
}
```

### PR DESCRIPTION
**Pull request by vbuberen**
## Description

This PR is a replacement for #11318 as it was agreed in that PR. Opened another PR as don't have access to push anything to that other fork used to create #11318.

Summary of changes and things to note:

- Added required ` buildFeatures` block in all `build.gradle` files for support of AGP 8.
- ~~Dropped step to install Java from CI as it is pre-installed on Github runners~~: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md UPD: Looks like workflow can't pick Java 17 on its own even though it is installed, so brought back the Java setup step.
- Dropped Jetifier everywhere as it is not needed and negatively influences build speed: https://adambennett.dev/2020/08/disabling-jetifier/
- Switched to new syntax to declare min, target and compile SDKs (e.g. instead of `compileSdkVersion` use `compileSDK`). **Note**, this would require projects using plugins to have at least AGP 7 as it mentioned here: https://developer.android.com/about/versions/13/setup-sdk
-  Updated AGP everywhere to 8.1.2 and Gradle wrapper to 8.3. Considering that some plugins still had `3.x` versions of AGP after this PR build speed should improve for such packages.
- Bumped minSDK to 19 for all plugins, because with current min Flutter version 19 is minimally supported anyway: https://docs.flutter.dev/reference/supported-platforms#deploying-flutter
- Dropped last mentions of `jcenter()` as it is not reliable and replaced with `mavenCentral()`.
- Changed declaration of Kotlin dependency to not mention `-jdk7` or `-jdk8` as it is not needed for quite a long time already and since release `1.8.x` is the default required way of declaring Kotlin dependency.
- I didn't update Kotlin as it was done in that other PR, because it would bring only issues to most projects. See https://github.com/fluttercommunity/plus_plugins/issues/2251 and https://github.com/juliansteenbakker/mobile_scanner/issues/729 for more information on the issue.
- Updated `annotation` Android dependency in all plugins.
- Removed redundant `gradle` folders in packages where they are not needed.
- Did some formatting for `build.gradle` files so they have the same position of blocks across plugins as it was confusing to update code in different places for every plugin.

## Related Issues

Closes #11266 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by russellwheatley** [comment]
@vbuberen - thank you for the PRs 🥳 . I will take a look at them next week 😄

**Comment by russellwheatley** [comment]
@vbuberen - The CI is failing because of the need for `compileSdkVersion` here: https://github.com/firebase/flutterfire/actions/runs/6533992367/job/17740279394?pr=11699#step:14:62

I've built it locally and it doesn't work with `compileSDK` but does build with `compileSdkVersion` 🤔

**Comment by vbuberen** [comment]
> I've built it locally and it doesn't work with compileSDK but does build with compileSdkVersion 🤔 

I will check it out a bit later today.

**Comment by vbuberen** [comment]
I made a typo there 🤦🏻 
It should be `compileSdk` not `compileSDK`

**Review by russellwheatley — APPROVED** [review]
Great work, @vbuberen 🥳

**Review by exaby73 — APPROVED** [review]

**Review by Lyokone — APPROVED** [review]

**Pull request merged**
