### PR TITLE
fix: upgrade `firebase` in firebase_analytics_web

### LINKED ISSUE #5202: 🐛 [firebase_analytics 7.1.0] Analytics dependency causes version solving to fail with other firebase core 1.0.0 packages
## Bug report

**Describe the bug**
Upgrading to flutter 2 fails although all firestore dependencies are updated to the latest versions.

### Steps to reproduce

flutter pub get:
Because every version of <package> from path depends on firebase_analytics 7.1.0 which depends on firebase_analytics_web ^0.2.0, every version of <package> from path requires firebase_analytics_web ^0.2.0.
And because every version of firebase_analytics_web depends on firebase ^7.3.0 which depends on http_parser ^3.0.0, every version of <package> from path requires http_parser ^3.0.0.
And because firebase_auth >=1.0.0 depends on firebase_auth_web ^1.0.0 which depends on http_parser ^4.0.0, <package> from path is incompatible with firebase_auth >=1.0.0.
So, because <app> depends on both firebase_auth 1.0.0 and <package> from path, version solving failed.

### Expected behavior

upgrade works with all firestore packages updated to the latest version

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.2 20D80 darwin-x64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ! CocoaPods 1.8.4 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "pub get" again.
pub finished with exit code 65

(since pub get fails as described above)
```

</details>

---

### PR DESCRIPTION
**Pull request by rrousselGit**
## Description

This upgrades `firebase` to fix version conflicts on `http_parser` between `firebase` and some of our packages

## Related Issues

fixes #5202 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by Salakar — APPROVED** [review]

**Comment by vmeretin** [comment]
```
Because every version of firebase_analytics from git depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, every version of firebase_analytics from git requires firebase ^7.3.0.
And because firebase >=7.0.0 <9.0.0 depends on http_parser ^3.0.0 and dio >=4.0.0-beta1 depends on http_parser ^4.0.0, firebase_analytics from git is incompatible with dio >=4.0.0-beta1.
So, because speak_peak depends on both firebase_analytics from git and dio ^4.0.0-beta6, version solving failed.
```

**Comment by Salakar** [comment]
> ```
> Because every version of firebase_analytics from git depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, every version of firebase_analytics from git requires firebase ^7.3.0.
> And because firebase >=7.0.0 <9.0.0 depends on http_parser ^3.0.0 and dio >=4.0.0-beta1 depends on http_parser ^4.0.0, firebase_analytics from git is incompatible with dio >=4.0.0-beta1.
> So, because speak_peak depends on both firebase_analytics from git and dio ^4.0.0-beta6, version solving failed.
> ```

`and dio >=4.0.0-beta1` this isn't one of our packages, what is it?

**Comment by rrousselGit** [comment]
> Because every version of firebase_analytics from git depends on firebase_analytics_web ^0.2.0 which

My understanding is that you're not using this fix, but instead using the published version.

It shouldn't be firebase_analytics that uses a git dependency, but firebase_analytics_web

**Comment by HofmannZ** [comment]
Was about to open a PR for this one, it's blocking us to use `firebase_analytics` at the moment.

You beat me to it ;)

**Comment by rrousselGit** [comment]
As I said, it's not firebase_analytics that should use a git dependency, but firebase_analytics_web

**Comment by rrousselGit** [comment]
firebase_analytics_web:
    git:
      url: https://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_analytics/firebase_analytics_web
      ref: update-analytics-web-dependency

**Comment by HofmannZ** [comment]
Branches are automatically delete from this repo, so use:

```
  firebase_analytics_web:
    git:
      url: https://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_analytics/firebase_analytics_web
      ref: master
```

**Comment by Salakar** [comment]
It has been published so you can also use the latest version now

**Pull request merged**
