### PR TITLE
[firebase_messaging] Android: background service refactoring

### PR DESCRIPTION
**Pull request by ened**
## Description

Currently, the FM plugin register 2 method channels (for FG and BG processing). 
This breaks when a App consists of more than 1 standard isolate, as it means on every isolate instantiation, the plugin will overwrite the previous background channel.

By setting the background channel within the plugin registration, it also introduced a memory leak (see #260). More importantly, when the foreground App is stopped, notifications may not always come through, as the background channel has been overwritten.

Update 2020/06/07:
The PR has been updated since and now uses a **FlutterEngine** object internally which removes most of the previously needed integration work on Android. The need to register a plugin registrant callback has been removed.
Additionally, analysis with LeakCanary has been done and memory leaks removed.

## Related Issues

This PR is based on #259; Merging that first is preferred to declutter this PR a bit.

#260 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

/cc @kroikie

### CODE REVIEW

**Comment by nhwilly** [comment]
On behalf of those of us that don't have the skills to troubleshoot at this level, a sincere thanks.

Great to see these problems identified and addressed in rapid succession.

**Comment by goody-h** [comment]
Glad to see this is a work in progress

**Comment by heaather** [comment]
Yes

**Comment by ened** [comment]
The PR has been refactored and includes a few more simplifications on the Android side, including:
 - Remove the need to register things in the host application by switching to a `FlutterEngine` internally
 - Remove all static variables, so that the host Activity won't leak
 - Remove further variables as needed

I'd appreciate if the community could help and test this PR.

If you are interested, please adjust the `dependency_overrides` field in your pubspec.yaml and add the following:

```
  firebase_messaging:
    git:
      url: https://github.com/ened/flutterfire.git
      path: packages/firebase_messaging
      ref: 254e43d18ba0862d9406fa0d872689d1961b3025
```

**Comment by ened** [comment]
@invertase - similarly, this PR could use someones attention. We are using it in production as else wise we'd run into memory leaks or similar. Also, it simplifies the integration on App side quite significantly.

**Comment by Salakar** [comment]
Thanks for this PR, its on our radar don't worry 🙃 we're close to shipping Functions & Storage reworks, after which we're focusing on messaging

**Comment by Salakar** [comment]
Also if you have any other PRs or issues that you're tracking and think we should look at please let us know below, thanks

**Pull request closed without merging**
