### PR TITLE
fix(firebase_messaging): various data types issues in remote message 

### PR DESCRIPTION
**Pull request by DFelten**
## Description

This pull request fixes the toMap method of RemoteMessage for firebase push images.

When sending a test push via firebase with an image the message looks like this:
```
{
    data =  {
        "fcm_options" = {
            image = "https://www.kostenlos.de/app/uploads/2020/11/slider_orange.jpg";
        };
    };
    messageId = 1605769654017551;
    sentTime = 1605769654;
}
```
The problem is, that `fcm_options` within `data` is a map and the `toMap` method currently needs data as a `Map<String, String>`. When changing it to `Map<String, dynamic>` it works.

## Related Issues

* https://github.com/FirebaseExtended/flutterfire/issues/4097#issuecomment-729827418

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by DFelten** [comment]
@googlebot I signed it!

**Comment by DFelten** [comment]
@googlebot I fixed it.

**Comment by Salakar** [comment]
@googlebot I consent.

**Comment by Salakar** [comment]
Thanks for this, I've updated to move the image out of data and to be under `message.notification.apple.imageUrl` - this now matches the same on android `message.notification.android.imageUrl`

**Pull request merged**
