### PR TITLE
[firebase_messaging] Implement android v2 embedding

### PR DESCRIPTION
**Pull request by kroikie**
Implement android v2 embedding

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
Hi @kroikie. This breaks `firebase_messaging` on Android for me, see https://github.com/FirebaseExtended/flutterfire/issues/1651#issue-538093464.

**Comment by eboye** [comment]
> Hi @kroikie. This breaks `firebase_messaging` on Android for me, see [#1651 (comment)](https://github.com/FirebaseExtended/flutterfire/issues/1651#issue-538093464).

+1 also for me

**Comment by pvsvamsi** [comment]
> Hi @kroikie. This breaks `firebase_messaging` on Android for me, see [#1651 (comment)](https://github.com/FirebaseExtended/flutterfire/issues/1651#issue-538093464).

+1 for me

**Comment by kroikie** [comment]
The use of `implementation` in the gradle dependency for FCM in the plugin removes visibility of the FirebaseMessagingService from Flutter's Android app. Adding the dependency to the Flutter App's build.gradle file should resolve this issue.

I'll update the README to add this step.

**Pull request merged**
