### PR TITLE
chore(firebase_remote_config): improve exception message

### PR DESCRIPTION
**Pull request by russellwheatley**
## Description

This exception occurs when there is no internet connection. I've captured ad update the exception to make it more user friendly and to avoid confusion.

Not sure how one would test this via the test suite so I've also just supplied the difference in output for the user.

Not sure if this is optimal as I guess it is a breaking change now the exception type has changed. Thoughts, @rrousselGit & @lesnitsky?

## Previous "Invalid Envelope" exception
Screenshot 2021-09-29 at 16 52 41

## Pull Request - no active internet exception
Screenshot 2021-09-29 at 16 51 46

## Related Issues

fixes https://github.com/FirebaseExtended/flutterfire/issues/6993

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by lesnitsky** [comment]
Seems ok to me, but I'm not sure I understand it's an error at all. Shouldn't default config be used instead?

**Comment by zmeggyesi** [comment]
Coming from issue #6993 , is this the _only_ condition when an "invalid envelope" can take place?

I'm using a physical device to test my app, and 
- It can reach the internet just fine, as verified via web browsing;
- There's a connectivity check prior to attempting to load remote config values, which passes

but I'm still getting this exception. Unfortunately, I can't really debug it further, due to not being able to dive into the Java platform code.

**Comment by russellwheatley** [comment]
@zmeggyesi I see. I wasn't able to reproduce whilst online. I'll close this PR as it doesn't solve the issue at hand.

**Comment by zmeggyesi** [comment]
@russellwheatley I wouldn't consider a *waste*, though, that exception message still needs some improvement, even if it's not the _core_ of the issue. :)

**Comment by russellwheatley** [comment]
@zmeggyesi  The problem is the PR changes the message to a "connection issue" when it might not be a connection problem as your issue demonstrates. So it is actually misleading.

**Pull request closed without merging**
