### PR TITLE
feat: initial `firebase_app_check` preview release

### PR DESCRIPTION
**Pull request by Salakar**
## Description

**TODO**
 - [x] Add CI workflow config (incl. `test_driver`)
 - [x] Update package descriptions and readmes & ensure all package versions are 0.0.1
 - [x] Add app-check documentation section & overview page at https://firebase.flutter.dev/docs/app-check/overview
 	- [x] Document installing debug provider for:
 		- [x] Web
 		- [x] iOS,macOS
 		- [x] Android
 - [x] Add to overview table on https://firebase.flutter.dev/ - under a `Preview` sub section header.

**Post release checklist**

 - [ ] Toggle visibility of `firebase_app_check_platform_interface` and `firebase_app_check_web` packages on pub.dev

## Related Issues

N/A

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Salakar** [comment]
@googlebot I consent.

**Comment by Salakar** [comment]
cc @mikehardy @Ehesp for `@googlebot I consent.`

**Comment by Ehesp** [comment]
@googlebot I consent.

**Review by russellwheatley — APPROVED** [review]
LGTM

**Comment by mikehardy** [comment]
@googlebot I consent

**Pull request merged**
