### PR TITLE
docs: fix readme typos

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
## Description

There are three changes: 

* Flutter**F**ire typo
* Comma before "and" (not an enumeration, so there should not be one)
* "send a pull request" → "open a pull request"; I think that "open" is idiomatic in this context

I did not add any changelog entries because I do not think that it is worth mentioning.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [x] No, this is *not* a breaking change. For sure not 😂

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by Salakar** [comment]
Thanks for this. If you're into reviewing docs, we'd love for you to review (if you're up for it) `/docs` for the new docs website, which can be viewed here: https://firebase.flutter.dev/docs

**Comment by creativecreatorormaybenot** [comment]
@Salakar Sounds good 👍🏽 Will take a look at the new docs when migrating asap anyway and then I can also review and potentially open a PR :)

**Comment by Salakar** [comment]
> @Salakar Sounds good 👍🏽 Will take a look at the new docs when migrating asap anyway and then I can also review and potentially open a PR :) (waiting for the other plugins to migrate to the new core)

Great :) thank you. Out of interest, which plugins are you waiting for?

**Comment by creativecreatorormaybenot** [comment]
@Salakar I guess only `firebase_storage` and `firebase_auth` because the others do not require `firebase_core` 🙂

**Comment by Salakar** [comment]
> @Salakar I guess only `firebase_storage` and `firebase_auth` because the others do not require `firebase_core` 🙂

Ok thanks, these will be up soon.

Ignoring build failure for now, this is a new issue that started occurring on the underlying iOS SDK since yesterday, Firebase iOS SDK team is aware: https://github.com/firebase/firebase-ios-sdk/issues/6047

**Pull request merged**
