### PR TITLE
fix crash where listeners are not removed when app quits

### PR DESCRIPTION
**Pull request by lidongze91**
This should solve #2526

### CODE REVIEW

**Comment by lidongze91** [comment]
> LGTM, please update the version in pubspec and changelog

Updated.

**Comment by lidongze91** [comment]
> Is there a way we can test this? Maybe in a Junit test?

Do we have existing junit test already? Or you would like me to add a new one.
(I don't see the test files within android dir)

**Comment by lidongze91** [comment]
@gching Could you do a code review when you get the chance? Thanks.

**Comment by lidongze91** [comment]
> LGTM

@bparrishMines Can you also merge it? I don't seem to have the access. Much Thanks.

**Comment by gching** [comment]
@lidongze91 Did we decide not to write unit tests for this PR?

**Comment by bparrishMines** [comment]
@cyanglaz  @kroikie I merged this without tests since its a trivial change and we would require java unit tests or expresso tests.

**Comment by gching** [comment]
@bparrishMines If possible, could you look into my PR #2605 for `firebase_auth`, it is a similar change but I wrote it with tests

**Pull request merged**
