### PR TITLE
[cloud_functions] Update version, dependencies, example

### PR DESCRIPTION
**Pull request by sbeitzel**
## Description

This does a few things, final cleanup for release of the cloud_functions_web package.

- Update dependencies in `cloud_functions` so that depending on cloud_functions will add `cloud_functions_web` to an application.
- Update [README.md](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_functions/cloud_functions_web/README.md) with appropriate version numbers.
- Add a web implementation to the `cloud_functions` example.

## Related Issues

flutter/flutter#45299

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by hterkelsen** [comment]
Oh no. I forgot to check in the review for `package:firebase_auth_web` that you have stub podspecs for iOS and stub gradle files for Android. Unfortunately, I think that both are required in order for this plugin to work with Flutter stable release.

@collinjackson @amirh can one of you confirm if stub podspecs and stub gradle files are still required?

**Comment by sbeitzel** [comment]
Yeah, it looks like they're required. Ugh. Is the right thing to split out adding those as a separate PR, to bump the `cloud_functions_web` version and then use that once it's been published?

**Comment by hterkelsen** [comment]
@sbeitzel yes. Send a PR with the stubs first and a version bump for `package:cloud_functions_web` (you can look at the other packages in here which have web implementation already for examples)

**Comment by sbeitzel** [comment]
Closing this PR and starting over, as the history has gotten very cluttered.

**Pull request closed without merging**
