### PR TITLE
feat(firebase_admob): integrate Admob with new core

### LINKED ISSUE #3209: [firebase_admob] version solving failed
**Describe the bug**
Today, I saw that many packages got updates. And I updated them. Unfortunately, I got below error on `firebase_admob`:

```
Because firebase_admob 0.9.3+4 depends on firebase_core ^0.4.2+1 and no versions of firebase_admob match >0.9.3+4 <0.10.0, firebase_admob ^0.9.3+4 requires firebase_core ^0.4.2+1.

So, because myapp depends on both firebase_core ^0.5.0 and firebase_admob ^0.9.3+4, version solving failed.
pub get failed (1; So, because myapp depends on both firebase_core ^0.5.0 and firebase_admob ^0.9.3+4, version solving failed.)
```

**To Reproduce**
pubspec.yaml:
```
firebase_core: ^0.5.0
firebase_admob: ^0.9.3+4
```

**Expected behavior**
The package `firebase_admob` should be updated to use new `firebase_core`...

**Flutter doctor**
```
[✓] Flutter (Channel dev, 1.21.0-9.0.pre, on Mac OS X 10.15.3 19D76, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)
```

### PR DESCRIPTION
**Pull request by kroikie**
Depend on firebase_core v 0.5.0 and migrate plugin to use firebase_core native SDK versioning features;

Firebase iOS SDK versions are now locked to use the same version defined in firebase_core.
Firebase Android SDK versions are now using the Firebase Bill of Materials (BoM) to specify individual SDK versions. BoM version is also sourced from firebase_core.

Fixes #3209

### CODE REVIEW

**Comment by Ehesp** [comment]
Is it worth adding in https://github.com/FirebaseExtended/flutterfire/issues/3236 as part of this too?

**Comment by kroikie** [comment]
Seems urgent enough to add in.

**Comment by Salakar** [comment]
Re: #3236 I don't think there's anything we need to do on the FlutterFire side other than make sure we're using the latest sdk, source: https://github.com/invertase/react-native-firebase/issues/4107

**Comment by kroikie** [comment]
Makes sense, we will have to update this dependency outside of setting Firebase Core since Firebase/AdMob is no longer updated and Firebase docs recommends direct dependency.

**Comment by Salakar** [comment]
@googlebot I consent.

**Comment by Salakar** [comment]
Both Android & iOS should be working now, have ran both locally:

image

**Review by Salakar — APPROVED** [review]

**Comment by john990** [comment]
> Makes sense, we will have to update this dependency outside of setting Firebase Core since Firebase/AdMob is no longer updated and Firebase docs recommends direct dependency.

Why Firebase/AdMob is no longer updated?!!!
Developing flutter applications can’t make money. Why do we use flutter?

**Comment by Salakar** [comment]
@john990 Firebase/AdMob podspec is just a shell to bring in the underlying google ads pods, what's being said here is that we'd in future rely on the google ads pods directly instead. Only the shell podspec is what's not being updated

**Comment by praveentcom** [comment]
When is the release planned for this PR?

**Comment by ianpark** [comment]
I think this update is still in prerelease. When is it going to be published?

https://pub.dev/packages/firebase_admob

**Comment by john990** [comment]
> @john990 Firebase/AdMob podspec is just a shell to bring in the underlying google ads pods, what's being said here is that we'd in future rely on the google ads pods directly instead. Only the shell podspec is what's not being updated

Wow, this is really good news, is it implemented entirely in Flutter?  Is there an approximate release date?  look forward to!

**Pull request merged**
