### PR TITLE
feat(firebase_storage): rework 

### PR DESCRIPTION
**Pull request by Salakar**
----

Co-authored-by: @ehesp 
Co-authored-by: @greghesp
Co-authored-by: @helenaford 
Co-authored-by: @kirstywilliams 
Co-authored-by: @salakar 

----

A `firebase_storage` dev release is now available - `5.0.0-dev.1`.

[NEW USAGE DOCUMENTATION](https://github.com/invertase/flutterfire/blob/%40invertase/storage_v1/docs/storage/usage.mdx).

----

### TODO

 - [x] Update CHANGELOG.md for PI & universal packages
 - [x] Update migration guide to include storage
 - [x] Review deprecation compatibility of old API and add any missing deprecated APIs where possible
 - [ ] Test remaining linked issues in related issues section below (the unchecked ones, add tests to confirm working)

## Description

As part of our on-going work for #2582 this is our Firebase Storage rework changes.

Overall, Firebase Storage has been heavily reworked to bring it inline with the federated plugin setup along with adding new features, documentation and many more unit and end-to-end tests (tested on Android, iOS & MacOS).

### `FirebaseStorage`

- **DEPRECATED**: Constructing an instance is now deprecated, use `FirebaseStorage.instanceFor` or `FirebaseStorage.instance` instead.
- **DEPRECATED**: `getReferenceFromUrl()` is deprecated in favor of calling `ref()` with a path.
- **DEPRECATED**: `getMaxOperationRetryTimeMillis()` is deprecated in favor of the getter `maxOperationRetryTime`.
- **DEPRECATED**: `getMaxUploadRetryTimeMillis()` is deprecated in favor of the getter `maxUploadRetryTime`.
- **DEPRECATED**: `getMaxDownloadRetryTimeMillis()` is deprecated in favor of the getter `maxDownloadRetryTime`.
- **DEPRECATED**: `setMaxOperationRetryTimeMillis()` is deprecated in favor of `setMaxUploadRetryTime()`.
- **DEPRECATED**: `setMaxUploadRetryTimeMillis()` is deprecated in favor of `setMaxUploadRetryTime()`.
- **DEPRECATED**: `setMaxDownloadRetryTimeMillis()` is deprecated in favor of `setMaxDownloadRetryTime()`.
- **NEW**: To match the Web SDK, calling `ref()` creates a new `Reference` at the bucket root, whereas an optional path (`ref('/foo/bar.png')`) can be used to create a `Reference` pointing at a specific location.
- **NEW**: Added support for `refFromURL`, which accepts a Google Storage (`gs://`) or HTTP URL and returns a `Reference` synchronously. 

### `Reference`

- **BREAKING**: `StorageReference` has been renamed to `Reference`.
- **DEPRECATED**: `getParent()` is deprecated in favor of `.parent`.
- **DEPRECATED**: `getRoot()` is deprecated in favor of `.root`.
- **DEPRECATED**: `getStorage()` is deprecated in favor of `.storage`.
- **DEPRECATED**: `getBucket()` is deprecated in favor of `.bucket`.
- **DEPRECATED**: `getPath()` is deprecated in favor of `.fullPath`.
- **DEPRECATED**: `getName()` is deprecated in favor of `.name`.
- **NEW**: Added support for `list(options)`.
  - Includes `ListOptions` API (see below).
- **NEW**: Added support for `listAll()`.
- **NEW**: `putString()` has been added to accept a string value, of type Base64, Base64Url, a [Data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) or raw strings.
  - Data URLs automatically set the `Content-Type` metadata if not already set.
- **NEW**: `getData()` does not require a `maxSize`, it can now be called with a default of 10mb.

### **NEW** `ListOptions`

The `list()` method accepts a `ListOptions` instance with the following arguments:

- `maxResults`: limits the number of results returned from a call. Defaults to 1000.
- `pageToken`: a page token returned from a `ListResult` - used if there are more items to query.

### **NEW** `ListResult`

A `ListResult` class has been added, which is returned from a call to `list()` or `listAll()`. It exposes the following properties:

- `items` (`List<Reference>`): Returns the list of reference objects at the current reference location.
- `prefixes` (`List<Reference>`): Returns the list of reference sub-folders at the current reference location.
- `nextPageToken` (`String`): Returns a string (or null) if a next page during a `list()` call exists.

### Tasks

Tasks have been overhauled to be closer to the expected Firebase Web SDK Storage API, allowing users to access and control on-going tasks easier. There are a number of breaking changes & features with this overhaul:

- **BREAKING**: `StorageUploadTask` has been renamed to `UploadTask` (extends `Task`).
- **BREAKING**: `StorageDownloadTask` has been renamed to `DownloadTask` (extends `Task`).
- **BREAKING**: `StorageTaskEvent` has been removed (see below).
- **BREAKING**: `StorageTaskSnapshot` has been renamed to `TaskSnapshot`.
- **BREAKING**: `pause()`, `cancel()` and `resume()` are now Futures which return a boolean value to represent whether the status update was successful.
  - Previously, these were `void` methods but still carried out an asynchronous tasks, potentially leading to uncaught exceptions.
- **BREAKING**: `isCanceled`, `isComplete`, `isInProgress`, `isPaused` and `isSuccessful` have now been removed. Instead you should subscribe to the stream (for paused/progress/complete/error events) or the task `Future` for task completion/errors.
- **BREAKING**: The `events` stream (now `snapshotEvents`) previously returned a `StorageTaskEvent`, containing a `StorageTaskEventType` and `StorageTaskSnapshot` Instead, the stream now returns a `TaskSnapshot` which includes the `state`.
- **BREAKING**: A task failure and cancellation now throw a `FirebaseException` instead of a new event.
- **DEPRECATED**: `events` stream is deprecated in favor of `snapshotEvents`.
- **DEPRECATED**: `lastSnapshot` is deprecated in favor of `snapshot`.

#### Example

The new API matches the Web SDK API, for example:

```dart
UploadTask task = FirebaseStorage.instance.ref('/notes.text').putString('My notes!');

// Optional
task.snapshotEvents.listen((TaskSnapshot snapshot) {
  print('Snapshot state: ${snapshot.state}'); // paused, running, complete
  print('Progress: ${snapshot.totalBytes / snapshot.bytesTransferred}');
}, onError: (Object e) {
  print(e); // FirebaseException
});

// Optional
task
  .then((TaskSnapshot snapshot) {
    print('Upload complete!');
  })
  .catchError((Object e) {
    print(e); // FirebaseException
  });
```

Subscribing to Stream updates and/or the tasks delegating Future is optional - if you require progress updates on your task use the Stream, otherwise the Future will resolve once its complete. Using both together is also supported.

### `SettableMetadata`

- **BREAKING**: `StorageMetadata` has been renamed to `SettableMetadata`.
- **BREAKING**: Fetching an objects metadata (e.g. via `getMetadata()` now returns a `FullMetadata` instance vs `StorageMetadata`.

----

## Related Issues & PRs

- [x] https://github.com/FirebaseExtended/flutterfire/issues/2301
- [x] https://github.com/FirebaseExtended/flutterfire/issues/811
- [x] https://github.com/FirebaseExtended/flutterfire/issues/2318
- [x] https://github.com/FirebaseExtended/flutterfire/issues/1314
- [x] https://github.com/FirebaseExtended/flutterfire/issues/684
- [x] https://github.com/FirebaseExtended/flutterfire/issues/2141
- [x] https://github.com/FirebaseExtended/flutterfire/issues/1935
- [x] https://github.com/FirebaseExtended/flutterfire/issues/609
- [ ] https://github.com/FirebaseExtended/flutterfire/issues/2127
- [x] https://github.com/FirebaseExtended/flutterfire/issues/2307
- [x] https://github.com/FirebaseExtended/flutterfire/issues/1280
- [x] https://github.com/FirebaseExtended/flutterfire/issues/1505
- [x] https://github.com/FirebaseExtended/flutterfire/issues/83
- [x] https://github.com/FirebaseExtended/flutterfire/issues/879
- [x] https://github.com/FirebaseExtended/flutterfire/issues/420 & https://github.com/FirebaseExtended/flutterfire/pull/2884
- [x] https://github.com/FirebaseExtended/flutterfire/pull/232

..and more (will be manually linked and closed following merge of this PR).

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by Ehesp** [comment]
@googlebot I consent.

**Comment by greghesp** [comment]
@googlebot I consent.

**Comment by Salakar** [comment]
A `firebase_storage` dev release is now available - `5.0.0-dev.1`.

**Comment by zmeggyesi** [comment]
Hi,

I believe I did find a few omissions from the changelogs during my migration:
- `StorageMetadata` has been renamed to `SettableMetadata`, constructor signature retained
- `Reference::getMetadata` now returns a `FullMetadata` instance
- `FullMetadata.creationTimeMillis` renamed to `FullMetadata.timeCreated`

So far, this is all I have, but if I find anything else during the actual _testing_, I'll be sure to comment.

**Comment by zmeggyesi** [comment]
When trying to upload a file, I get the following exception:
```
D/AndroidRuntime(16635): Shutting down VM
E/AndroidRuntime(16635): FATAL EXCEPTION: main
E/AndroidRuntime(16635): Process: tech.provingground.site_overwatch, PID: 16635
E/AndroidRuntime(16635): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/AndroidRuntime(16635): 	at io.flutter.plugins.firebase.storage.FlutterFirebaseStoragePlugin.parseMetadata(FlutterFirebaseStoragePlugin.java:99)
E/AndroidRuntime(16635): 	at io.flutter.plugins.firebase.storage.FlutterFirebaseStorageTask.parseUploadTaskSnapshot(FlutterFirebaseStorageTask.java:106)
E/AndroidRuntime(16635): 	at io.flutter.plugins.firebase.storage.FlutterFirebaseStorageTask.parseTaskSnapshot(FlutterFirebaseStorageTask.java:131)
E/AndroidRuntime(16635): 	at io.flutter.plugins.firebase.storage.FlutterFirebaseStorageTask.getTaskEventMap(FlutterFirebaseStorageTask.java:296)
E/AndroidRuntime(16635): 	at io.flutter.plugins.firebase.storage.FlutterFirebaseStorageTask.lambda$null$3$FlutterFirebaseStorageTask(FlutterFirebaseStorageTask.java:235)
E/AndroidRuntime(16635): 	at io.flutter.plugins.firebase.storage.-$$Lambda$FlutterFirebaseStorageTask$LM7xczfI-_C_rFWVuwmxMyoLPsM.run(Unknown Source:6)
E/AndroidRuntime(16635): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(16635): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(16635): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(16635): 	at android.app.ActivityThread.main(ActivityThread.java:7397)
E/AndroidRuntime(16635): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16635): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(16635): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
I/Process (16635): Sending signal. PID: 16635 SIG: 9
Lost connection to device.
```

I managed to track this down to `firebase-storage-platform-interface-1.0.0-dev.1` -> `method_channel_reference.dart:147`, but closer than that, I don't really know where it might be coming from.

What else do you need from me to look into it?

**Comment by greghesp** [comment]
@zmeggyesi Do you have a minimal code sample you can provide that is causing the error?

**Comment by zmeggyesi** [comment]
@greghesp I'll try to create a runnable demo tomorrow, but just in case it rings a bell for someone, this is the _immediate context_:
```
      Reference child = FirebaseStorage.instance.ref().child("/sites/${_site.id}/images/${Uuid().v4()}");
      File f = File(pf.path);
      UploadTask putFile = child.putFile( // this line is throwing the exception
          f,
          SettableMetadata(
            cacheControl: "public, max-age=3600",
            customMetadata: {
             /* snip */
            },
          ));
      putFile.snapshotEvents.listen((event) {
        dev.log("Upload state: ${event.state}");
      });
      putFile.whenComplete(() async {
        String url = await child.getDownloadURL();
        setState(() {
          /* snip */
        });
      });
```

**Comment by Salakar** [comment]
I think I see the issue @zmeggyesi, I'll push a dev release with a fix in an hour or so. Will ping here

**Comment by zmeggyesi** [comment]
@Salakar Do I need to update the pubspec ref to load your fix, or just `pub upgrade` to have it load the latest version?

**Comment by zmeggyesi** [comment]
@Salakar As of commit `a1c4ba2434335be9df95fd3bcf1a57d5101f9a84`, uploading works on Android. Thank you for the change!

As for iOS, I could not find any _immediately_ obvious problems so far.

**Pull request merged**
