### PR TITLE
fix(ios,dynamic_links): fixed issue with overwriting correct url with null one

### PR DESCRIPTION
**Pull request by madmag77**
## Description

This PR is intended to fix the issue https://github.com/FirebaseExtended/flutterfire/issues/1506 for iOS. The problem is that for iOS app that is being run by universal link the sequence of calls look like this:
1. 
```
- (BOOL)application:(UIApplication *)application
    continueUserActivity:(NSUserActivity *)userActivity
      restorationHandler:(void (^)(NSArray *))restorationHandler 
``` 
is being called with the proper link. Then the link is checked and being stored in `_initialLink` because we didn't call `getInitialLink` from flutter yet (it's too early).

2. 
```
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> *)options
```
 is being with link that looks like `“BUNDLE_ID://google/link/?dismiss=1&is_weak_match=1”` - this link can't be parsed and thus ends up in the same `_initialLink` but with property `url = nil`. So, basically we overwrite proper `url` with `nil url `in `_initialLink`.

3. Function `getInitialLink` is being called from flutter and will return `_initialLink` with nil in the `url` property so the flutter app can't use proper url.

This is like a race condition - sometimes step 2 being called after 3 and the flutter app gets proper url (but it's rarely).

This is only for cold start of the app. On the warm start everything works fine.

## Related Issues

https://github.com/FirebaseExtended/flutterfire/issues/1506 (ios only)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by madmag77** [comment]
Hey @Ehesp, could you help to review it or advise smb? Thanks a lot

**Review by MarceLifeBites — APPROVED** [review]
@madmag77 you save my day, i was struggling with these race conditions for a lot of hours, and i check your solution and works like a charm, thx!

**Comment by sanekyy** [comment]
Hello @madmag77. Your PR works great. Thanks.

**Comment by madmag77** [comment]
Thanks @MarceLifeBites, @sanekyy. Looking forward to somebody else approving this PR so I can merge it and not using a fork :)

**Review by adammacdonald — APPROVED** [review]

**Review by Salakar — APPROVED** [review]
Thanks, LGTM.

**Comment by Salakar** [comment]
Thanks everyone for confirming this fix - am merging now - will get a release out after the Firebase Summit.

**Pull request merged**
