### PR TITLE
[firebase_remote_config] Fix Future already completed RemoteConfig.instance

### PR DESCRIPTION
**Pull request by collinjackson**
Migrates flutter/plugins#1966 by @IchordeDionysos

I ended up rewriting it a bit.

Note: It seems the plugin was working fine and the behavior is covered by a test, but there was a spurious error message in the logs. This PR is removing the error message in the logs, and I don't think I can easily cover that in a test.

Fixes flutter/flutter#38060

### CODE REVIEW

**Comment by IchordeDionysos** [comment]
I still get the error with this merge request 🤔

**Comment by kroikie** [comment]
@IchordeDionysos would you mind filling an issue with the details of what you are seeing so we can have a closer look?

**Comment by IchordeDionysos** [comment]
@kroikie I've filed an issue with an MVCE so you can easily see the problem yourself:
https://github.com/FirebaseExtended/flutterfire/issues/120

**Comment by IchordeDionysos** [comment]
@collinjackson @kroikie This issue does not seem to be fixed by this pull request: #195 195

**Pull request merged**
