### PR TITLE
feat(firebase_analytics): Improve `FirebaseAnalyticsObserver` so that it also fires events when the modal route changes.

### PR DESCRIPTION
**Pull request by zvikarp**
## Description

Currently,`FirebaseAnalyticsObserver` extends `RouteObserver<PageRoute<dynamic>>` and logs `PageRoute` screen views, but not `PopupRoute` screen views. We use `ModalBottomSheetRoute` that extends `PopupRoute` and therefor these screens were not logged by the observer.

I have changed `PageRoute` to `ModelRoute`, as both `PageRoute` and `PopupRoute` extend it. It well can be that this functionality would result in logging screens other users didn't expect to log, in that case, we can update this PR with (a) a flag `logPopupRoutes` that would default to false, or (b) add a `routesTypes` list that would default to [PageRoute], and we would only log types from that list (this way we the developer can add specific routes types to log).

## Related Issues

I haven't found any related issues, and didn't see a need to open one - as we have the solution :) 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by russellwheatley** [comment]
Hi @zvikarp, thanks for the PR! However, the example is just a demonstration of how to capture simple page changes. It's not supposed to be comprehensive, that is up to the developer 😄.

**Comment by zvikarp** [comment]
Hi @russellwheatley thank you for commenting!

I'm sorry, I didn't understand it, I did not update the example. How can I use the firebase observer to track `PopupRoute` as the current observer only tracks `PageRoute`, and `PopupRoute` does not extend `PageRoute`?

**Comment by russellwheatley** [comment]
My mistake! Sorry, I misunderstood what you were aiming at. I've reopened it 🙏

**Review by lesnitsky — CHANGES_REQUESTED** [review]
> in that case, we can update this PR with (a) a flag logPopupRoutes that would default to false, or (b) add a routesTypes list that would default to [PageRoute], and we would only log types from that list (this way we the developer can add specific routes types to log).

I'm thinking (b) should be a preferred API, since it allows for more granular filtering of the route types that the user expects to be sent to analytics

**Comment by zvikarp** [comment]
Thank you @lesnitsky for the changes request, I'll circle back soon with an update.

**Comment by zvikarp** [comment]
Hey @lesnitsky , I have added a `RouteFilter`:

```
/// [RouteFilter] allows to filter out routes that should not be tracked.
///
/// By default, only [PageRoute]s are tracked.
typedef RouteFilter = bool Function(ModalRoute<dynamic> route);
```

**Review by lesnitsky — APPROVED** [review]

**Comment by russellwheatley** [comment]
PR is ready to merge but we're fixing CI at the moment 🙏

**Comment by russellwheatley** [comment]
Hey @zvikarp, if you fix these issues, I believe it should resolve the CI jobs that are failing:
```bash
[firebase_analytics]:   error - lib/src/observer.dart:103:23 - The argument type 'Route<dynamic>' can't be assigned to the parameter type 'ModalRoute<dynamic>'. - argument_type_not_assignable
[firebase_analytics]:   error - lib/src/observer.dart:111:23 - The argument type 'Route<dynamic>?' can't be assigned to the parameter type 'ModalRoute<dynamic>'. - argument_type_not_assignable
[firebase_analytics]:   error - lib/src/observer.dart:119:23 - The argument type 'Route<dynamic>?' can't be assigned to the parameter type 'ModalRoute<dynamic>'.
```

**Comment by zvikarp** [comment]
Hey @russellwheatley , sorry for that! I fixed it :)

**Review by russellwheatley — APPROVED** [review]
LGTM

**Pull request merged**
