### PR TITLE
chore(firebase_performance): remove redundant firebase_core dependency

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
## Description

So I was trying to figure out why the plugin was `firebase_performance` plugin was not working for tracing on app start. And because of the `firebase_core` dependency I was mislead into believing I would have to call [`Firebase.initializeApp`](https://pub.dev/documentation/firebase_core/latest/firebase_core/Firebase/initializeApp.html) first, which would be detrimental because it is asynchronous (so I cannot create the trace synchronously).

Anyway, it turns out I went through the whole source code and there is not a single reference to `firebase_core`, not in the native code or the Dart code. So the dependency is there for no reason whatsoever and only misleading.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by russellwheatley** [comment]
hey @creativecreatorormaybenot, we do actually use `firebase_core` for ascertaining the firebase [android bom version](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_performance/firebase_performance/android/build.gradle#L24). In future, this dependency will also be used by `firebase_performance` like all other plugins that have been reworked.

**Comment by creativecreatorormaybenot** [comment]
@russellwheatley Thanks - I am wondering, why did CI pass then?

**Comment by creativecreatorormaybenot** [comment]
@russellwheatley And thanks for the rework input - is there any timeline for the `firebase_performance` plugin btw? I now wrote my own web bridge for our use case, but I would love to contribute. It is just that I cannot do so before it is reworked (I assume).

See also #6649.

**Comment by russellwheatley** [comment]
> @russellwheatley Thanks - I am wondering, why did CI pass then?

It passed because the example app still references `firebase_core` packages [here](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_performance/firebase_performance/example/pubspec.yaml#L17).

> @russellwheatley And thanks for the rework input - is there any timeline for the `firebase_performance` plugin btw? I now wrote my own web bridge for our use case, but I would love to contribute. It is just that I cannot do so before it is reworked (I assume).
> 
> See also #6649.

We're not sure on timeframe but a pretty conservative estimate would be before the end of the year.

**Comment by creativecreatorormaybenot** [comment]
@russellwheatley If there is any way I can contribute, let me know.

**Pull request closed without merging**
