### PR TITLE
[firebase_crashlytics] Add macOS support

### PR DESCRIPTION
**Pull request by cbenhagen**
## Description

Add macOS support.

## Related Issues

https://github.com/FirebaseExtended/flutterfire/issues/1653

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by cbenhagen** [comment]
The macOS example is complaining about a missing `GoogleService-Info.plist`. In the other PRs I copied the file from the iOS example. But here it does not contain one. @franciscojma86 can you create one?

**Comment by viktor-morin** [comment]
Any relation to my issue?
[https://github.com/FirebaseExtended/flutterfire/issues/1951](https://github.com/FirebaseExtended/flutterfire/issues/1951)

**Comment by cbenhagen** [comment]
@viktor-morin No, unless you forgot to provide your own `GoogleService-Info.plist` in your app. The example missing that file only affects testing.

**Comment by viktor-morin** [comment]
@cbenhagen 
Yeah sorry isn't related. But do you have any insight in why crashlytics dosnt work for iOS?

**Comment by cbenhagen** [comment]
@viktor-morin I don't know. Please do not hijack other issues.

**Comment by collinjackson** [comment]
> @cbenhagen
> Yeah sorry isn't related. But do you have any insight in why crashlytics dosnt work for iOS?

There is a known issue affecting iOS with a pending fix here: https://github.com/FirebaseExtended/flutterfire/pull/1782

I imagine that fix will benefit macOS as well.

**Comment by viktor-morin** [comment]
> > @cbenhagen
> > Yeah sorry isn't related. But do you have any insight in why crashlytics dosnt work for iOS?
> 
> There is a known issue affecting iOS (keys not getting reported) with a pending fix here: #1782
> 
> I imagine that fix will benefit macOS as well.

@collinjackson 
I don't want to to hijack this thread but is there a way to get that fix now? Get an dev version of this package?

**Comment by collinjackson** [comment]
> > > @cbenhagen
> > > Yeah sorry isn't related. But do you have any insight in why crashlytics dosnt work for iOS?
> > 
> > 
> > There is a known issue affecting iOS (keys not getting reported) with a pending fix here: #1782
> > I imagine that fix will benefit macOS as well.
> 
> @collinjackson
> I don't want to to hijack this thread but is there a way to get that fix now? Get an dev version of this package?

You can use a git dependency with a package in a folder, pointing to the ref of the PR. More info [here](https://flutter.dev/docs/development/packages-and-plugins/using-packages).

**Comment by viktor-morin** [comment]
> > > > @cbenhagen
> > > > Yeah sorry isn't related. But do you have any insight in why crashlytics dosnt work for iOS?
> > > 
> > > 
> > > There is a known issue affecting iOS (keys not getting reported) with a pending fix here: #1782
> > > I imagine that fix will benefit macOS as well.
> > 
> > 
> > @collinjackson
> > I don't want to to hijack this thread but is there a way to get that fix now? Get an dev version of this package?
> 
> You can use a git dependency with a package in a folder, pointing to the ref of the PR. More info [here](https://flutter.dev/docs/development/packages-and-plugins/using-packages).
@collinjackson 
Thanks for helping out, unfortunately didn't that solve the issue.

**Comment by cbenhagen** [comment]
@viktor-morin && @collinjackson please keep communication about other issues out of this PR unless they are related. Of course every fix for iOS code will most likely fix them for macOS as well and I highly appreciate those efforts.

**Pull request merged**
