### PR TITLE
[skip ci] don't run Cirrus on tags

### PR DESCRIPTION
**Pull request by cyanglaz**
flutterfire version for https://github.com/flutter/plugins/pull/2396

### CODE REVIEW

**Comment by cyanglaz** [comment]
@fkorotkov Could you take a look at this :)

**Comment by fkorotkov** [comment]
LGTM. Should've add `[skip ci]` right away to actually skip CI. 😅

**Comment by cyanglaz** [comment]
@fkorotkov yeah, didn't know about it until the release. :/

**Comment by cyanglaz** [comment]
The Ci failure is caused by cancellation. We don't need to run all the tests for this PR since it is just a cirrus script change. Planning to merge it on red.

**Pull request merged**
