### PR TITLE
[firebase_auth] Added support for dynamicLinkDomain property in ActionCodeSettings

### PR DESCRIPTION
**Pull request by mdudek**
## Description

The dynamicLinkDomain property of ActionCodeSettings was not exposed to flutter API.

### CODE REVIEW

**Comment by mdudek** [comment]
> @googlebot I signed it!

**Comment by mdudek** [comment]
I have fixed tests & code formatting, but I don't know how to fix failed 'analyze' & 'publishable' checks.

**Comment by coolnalu** [comment]
Kinda need this to work lol.

**Comment by vinicius-animo** [comment]
Any evolution here, @mdudek , @googlebot ?

**Comment by mdudek** [comment]
@googlebot I consent

**Comment by mdudek** [comment]
It seems that the checks failed because it's using published version of firebase_auth_platform_interface package and not the updated one from git. Anyone could help me to resolve these issues?

**Comment by ErikHellman** [comment]
Any idea when this can be merged and released? We need this if to be able to use a custom domain.

**Comment by mdudek** [comment]
Unfortunately, I have no answer to help with failing check and merge this PR. I had to rebase my fork to be synced with current version of FlutterFire, previous check issues disappeared, but there is a lot of new ones.  ;-(

Currently I'm pushed to use my fork of FlutterFire in Flutter projects, it works nicely.

**Comment by theochampion** [comment]
Any updates on this? This is really needed for custom domains https://github.com/FirebaseExtended/flutterfire/issues/2355

**Comment by athornz** [comment]
@mdudek I think a rebase on master is needed here. There are 1200 changed files which would make it hard for anyone to review!

**Comment by mdudek** [comment]
Hi @athornz,  I have rebased this PR, but there is still a lot of failed checks. It seems that check tasks are using published version of firebase_auth_platform_interface package and not the updated one from this PR. I really don't know how to fix it.

**Comment by PaulTR** [comment]
I'm going to try to implement these changes on my own branch on Monday and see if I can't work out what's going on with the PR :)

**Comment by PaulTR** [comment]
Unfortunately I couldn't get this to build properly on my machine when I made the changes to a current branch of master. Would you mind rebasing and running all the tests?

**Comment by mdudek** [comment]
Ok, I will try to rebase my PR again, I hope it will take less time than last rebase ...

**Comment by kroikie** [comment]
@mdudek any luck with the rebasing?

**Comment by mdudek** [comment]
Just rebased, some checks are still failing, probably same reason as before...

**Comment by mdudek** [comment]
It seem to be ready to approve.

**Comment by bkoznov** [comment]
Would love this to be merged, it is super useful and I don't like being off flutterfire main branch.

**Comment by ThouShawNotPass** [comment]
Looks like the only thing left to get this PR across the finish line is to get some of our friends to review this. They're probably super busy, but let's see if it helps to tag them (sorry to bother if this is not ready yet):
@amirh 
@bparrishMines 
@collinjackson 
@kroikie 

I would love to get this in master, it's currently blocking the password-less sign-in feature for custom domains and this is the only known workaround [see this issue](https://github.com/FirebaseExtended/flutterfire/issues/1571#issuecomment-619387391).

**Comment by Salakar** [comment]
This is now already supported on the current pre-release that is on master: https://pub.dev/documentation/firebase_auth_platform_interface/2.0.0-dev.1/firebase_auth_platform_interface/ActionCodeSettings/dynamicLinkDomain.html

Going to close this PR now as it's no longer required. Thank you though for contributing!

**Pull request closed without merging**
