### PR TITLE
[firebase_auth_web] creationTime and lastSignInTime are not parsable by DateTime.parse

### PR DESCRIPTION
**Pull request by GregorySech**
## Description

While trying firebase_auth_web with signInAnonymously I've found an un-serialization error.
creationTime and lastSignInTime are RFC1123 formatted and `dart:core`'s DateTime.parse is unable to parse it.
I used HttpDate.parse which is able to parse RFC1123 in a correct DateTime.  

## Related Issues

None. Maybe I should open it for future reference?

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by collinjackson** [comment]
@hterkelsen I'm wondering if we can write a test for this.

**Comment by hterkelsen** [comment]
In order to write a test for this we would need a live Firebase app to send us real responses.

**Comment by collinjackson** [comment]
> In order to write a test for this we would need a live Firebase app to send us real responses.

I think we can use the same app that we use for the mobile integration tests.

**Comment by hterkelsen** [comment]
This isn't going to work. We can't use `dart:io` in `firebase_auth_web` since `dart:io` is unavailable on the web.

**Comment by hterkelsen** [comment]
Try using this: https://pub.dev/documentation/http_parser/latest/http_parser/parseHttpDate.html

**Comment by GregorySech** [comment]
@hterkelsen HttpDate's implementation seems to have no real dependency on dart:io beside HttpException. Maybe an issue should be raised to have HttpDate parsing of RFC1123 available to dart:core?

**Comment by collinjackson** [comment]
Seems like we've run out of Cirrus credits again but the important tests are passing.

**Pull request merged**
