### PR TITLE
chore: update lower bound dart dependency to 2.0.0

### PR DESCRIPTION
**Pull request by 2ZeroSix**
## Description

update sdk dependency: 2.0.0-dev.* => 2.0.0

## Related Issues

same issue: https://github.com/flutter/flutter/issues/56930

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by 2ZeroSix** [comment]
@Salakar did the same for cloud_functions as part of this PR #2519

**Comment by Salakar** [comment]
@2ZeroSix awesome - thanks for sorting :) beat me to it! Will get this reviewed tomorrow

**Comment by domesticmouse** [comment]
Hi @2ZeroSix,

Looking at https://github.com/flutter/flutter/issues/56930 this should probably be updated to make Dart 2.1.0 the minimum version, yeah?

thanks!

**Comment by 2ZeroSix** [comment]
@domesticmouse I don’t know why @cyanglaz decided to upgrade version to 2.1.0.

The fix is to use stable version higher than dev versions used in pubspec currently.

Min stable dart version after 2.0.0-dev.* is 2.0.0 (I checked versioning docs and repo history to be sure) and I don’t see any reason to use 2.1.0

**Comment by domesticmouse** [comment]
@2ZeroSix SGTM.

PTAL @kroikie, this PR will help with CI issues.

**Comment by cyanglaz** [comment]
I think 2.0.0 is also fine as the plugins are not using any new language features.
Although 2.0.0 and 2.1.0 are both pretty old.

**Comment by cyanglaz** [comment]
FYI. I enabled the CI on the flutter/plugin repo to use master channel for the publishing check in https://github.com/flutter/plugins/commit/e26634c4ac1def13776769912d3873ec17316fbc
We might want to do the same for this repo if haven't already.

**Comment by domesticmouse** [comment]
Thanks @cyanglaz, created https://github.com/FirebaseExtended/flutterfire/pull/2578 with this change

**Comment by 2ZeroSix** [comment]
recently #2589 with these changes for [firebase_admob] was merged.
Should I do something to make this merged? Maybe split this into 14 pull requests (1 per package)?

**Pull request merged**
