### PR TITLE
feat(crashlytics): Move iOS deployment target from 10 to 9

### PR DESCRIPTION
**Pull request by miguelslemos**
## Description

Since firebase-ios-sdk 7.3.0 bumps down crashlytics minimum deployment target to **9.0** . This plugin can also support iOS 9+. 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

https://github.com/firebase/firebase-ios-sdk/pull/7053

### CODE REVIEW

**Review by reinaldomoreira — APPROVED** [review]

**Comment by miguelslemos** [comment]
Should I downgrade flutter_core too? Because flutter_core is a dependency from flutter_crashlytics

**Comment by Salakar** [comment]
If `core` from the iOS SDK supports iOS 9 then we should probably make that one iOS 9 too if we accept this as Crashlytics requires core to function.

cc @mikehardy - thoughts?

**Comment by mikehardy** [comment]
Expediency (single target) vs widest compatibility. I think there are a few that do 9, analytics as well maybe? We decided for expediency when bumping to 10 before based on version install stats and other ecosystems moving to 10 minimum. If the version story will be complicated I'd encouraged it to match upstream exactly with a full package audit, then yes core is lowest to match.

**Comment by russellwheatley** [comment]
Closing in favour of this PR: https://github.com/FirebaseExtended/flutterfire/pull/6757

**Pull request closed without merging**
