### PR TITLE
[cloud_functions] Add macOS support

### PR DESCRIPTION
**Pull request by cbenhagen**
## Description

Add macOS support.

## Related Issues

https://github.com/FirebaseExtended/flutterfire/issues/1653

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by franciscojma86** [comment]
Thanks for the PR! Can you please share the implementation code as in https://github.com/FirebaseExtended/flutterfire/pull/1704? You can do so in https://github.com/FirebaseExtended/flutterfire/pull/1706 and https://github.com/FirebaseExtended/flutterfire/pull/1705 as well.

**Comment by cbenhagen** [comment]
Sure, will do that. Do you have any idea how we should handle tests for the macOS plugins?

**Comment by franciscojma86** [comment]
I believe you can write XCTests, but they won't be run on the CI. Is this correct @collinjackson?

**Comment by cbenhagen** [comment]
@franciscojma86 rebased and shared the implementation as proposed. Still missing tests.

**Comment by franciscojma86** [comment]
XCTests are still not supported for macOS, so as long as the PR passes the integration tests, you should be good to land this

**Comment by cbenhagen** [comment]
Tests seem to fail for unrelated issues..

**Pull request merged**
