### PR TITLE
[cloud_firestore_web] Ensure Query pagination methods encode values.

### PR DESCRIPTION
**Pull request by ditman**
## Description

This change ensures that the package:firestore Query objects are created with properly encoded values when done so from the start/end (pagination) methods.

This also adds some Timestamps to the unit tests to verify the behavior of Timestamp -> DateTime.

_(There are some integration tests in cloud_firestore that cover this behavior further.)_

## Related Issues

Fixes https://github.com/FirebaseExtended/flutterfire/issues/2153

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by ditman** [comment]
(The push above is unrelated. I didn't add a version bump because it's just a minor fix in a test file to appease the analyzer, I'm not planning in publishing that)

**Comment by amrfarid140** [comment]
Ah! this slipped through the cracks when we did it for mobile. Good catch @ditman .

**Comment by Ches1422** [comment]
[firebase-monetization-tips-master.1.zip](https://github.com/FirebaseExtended/flutterfire/files/4347667/firebase-monetization-tips-master.1.zip)

**Comment by Ches1422** [comment]
[google-site-kit.1.2.0.zip](https://github.com/FirebaseExtended/flutterfire/files/4347683/google-site-kit.1.2.0.zip)

**Comment by ditman** [comment]
I'm merging this, I repeated the last failing check and it passed, and there's 2 approvals.

**Pull request merged**
