### PR TITLE
[Firebase_messaging] Fix Deprecated API usage

### PR DESCRIPTION
**Pull request by ashutoshkmr**
## Description

 Fix Deprecated API usage

## Related Issues

#122 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by genert** [comment]
Looks good. 👍

**Comment by zukinaru** [comment]
Hi @ashutoshkmr and @genert 
Because of this update, i get erro4 on my build:
```
Step #1: Note: Recompile with -Xlint:unchecked for details.
Step #1:
Step #1: /builder/home/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.6/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseMessagingService.java:143: error: method findAppBundlePath in class FlutterMain cannot be applied to given types;
Step #1:
Step #1: String appBundlePath = FlutterMain.findAppBundlePath();
Step #1:
Step #1: ^
Step #1:
Step #1: required: Context
Step #1:
Step #1: found: no arguments
Step #1:
Step #1: reason: actual and formal argument lists differ in length
```

any idea to solve this ?

This is urgentm Because my project need to deliver asap....

**Comment by ashutoshkmr** [comment]
> Hi @ashutoshkmr and @genert
> Because of this update, i get error on my build:
> 
> ```
> Step #1: Note: Recompile with -Xlint:unchecked for details.
> Step #1:
> Step #1: /builder/home/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.6/android/src/main/java/io/flutter/plugins/firebasemessaging/FlutterFirebaseMessagingService.java:143: error: method findAppBundlePath in class FlutterMain cannot be applied to given types;
> Step #1:
> Step #1: String appBundlePath = FlutterMain.findAppBundlePath();
> Step #1:
> Step #1: ^
> Step #1:
> Step #1: required: Context
> Step #1:
> Step #1: found: no arguments
> Step #1:
> Step #1: reason: actual and formal argument lists differ in length
> ```
> 
> Above error is on line 143...
> 
> any idea to solve this ?
> 
> This is urgent Because my project need to deliver asap....

what is the dependency version on you build.gradle ?
should be   api 'com.google.firebase:firebase-messaging:20.0.0'

**Comment by zukinaru** [comment]
below are my dependencies at `app/builr.gradle`:

dependencies {
//    androidTestImplementation 'androidx.test.runner:1.1.1'
//    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
//    implementation 'com.google.firebase:firebase-core:16.0.1'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.google.android.gms:play-services-location:16.0.0'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.facebook.android:facebook-android-sdk:[5,6)'
}`

**Comment by zukinaru** [comment]
Temporary solution for me:

`firebase_messaging: ">=5.0.2 <5.1.5"`

**Comment by zukinaru** [comment]
> > It's flutter prj
> > in pubspec.yaml:
> > `firebase_messaging: ^5.0.2`
> > below are my dependencies at `app/build.gradle`:
> > ```
> > dependencies {
> > 
> >     testImplementation 'junit:junit:4.12'
> >     androidTestImplementation 'com.android.support.test:runner:1.0.2'
> >     androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
> > 
> >     implementation 'com.google.android.gms:play-services-location:16.0.0'
> >     implementation 'com.crashlytics.sdk.android:crashlytics:2.10.0'
> >     implementation 'com.android.support:multidex:1.0.3'
> >     implementation 'com.facebook.android:facebook-android-sdk:[5,6)'
> > }
> > ```
> 
> did you try updating your android sdk ?

I am using google cloud build via docker,

Btw now solved temporary by change this on pubspec.yaml

`firebase_messaging: ">=5.0.2 <5.1.5"`

**Comment by ashutoshkmr** [comment]
> > > It's flutter prj
> > > in pubspec.yaml:
> > > `firebase_messaging: ^5.0.2`
> > > below are my dependencies at `app/build.gradle`:
> > > ```
> > > dependencies {
> > > 
> > >     testImplementation 'junit:junit:4.12'
> > >     androidTestImplementation 'com.android.support.test:runner:1.0.2'
> > >     androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
> > > 
> > >     implementation 'com.google.android.gms:play-services-location:16.0.0'
> > >     implementation 'com.crashlytics.sdk.android:crashlytics:2.10.0'
> > >     implementation 'com.android.support:multidex:1.0.3'
> > >     implementation 'com.facebook.android:facebook-android-sdk:[5,6)'
> > > }
> > > ```
> > 
> > 
> > did you try updating your android sdk ?
> 
> Which Android sdk needed to use your update ?
> 
> I am using google cloud build via docker,
> 
> Btw now solved temporary by change this on pubspec.yaml
> 
> `firebase_messaging: ">=5.0.2 <5.1.5"`

 FlutterMain.findAppBundlePath() does not require to pass context in the latest flutter api

https://api.flutter.dev/javadoc/io/flutter/view/FlutterMain.html#findAppBundlePath-android.content.Context-

What is your flutter version ?

**Pull request merged**
