### PR TITLE
fix(firebase_messaging): Ensure `onMessage` callback is consistently called on `iOS` platform.

### PR DESCRIPTION
**Pull request by russellwheatley**
## Description

See title.

## Related Issues

fixes https://github.com/FirebaseExtended/flutterfire/issues/8042

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by Salakar — APPROVED** [review]

**Comment by GKPK** [comment]
I suggest, please add below condition at line 479 rather than removing the callback:

Now:
image

Suggested:
```
        if (@available(iOS 11, *)) {
            // Don't send an event for iOS 11 and up as userNotificationCenter will send the event for us, we don't want to duplicate them.
        } else {
            [_channel invokeMethod:@"Messaging#onMessage" arguments:notificationDict];
        }

      completionHandler(UIBackgroundFetchResultNoData);
```

Other changes are fine.

**Comment by GKPK** [comment]
Any update on this PR, when this will be approved and released with a next version, as this fix is important.

**Comment by Salakar** [comment]
> I suggest, please add below condition, rather than removing the callback:
> 
> Now: image
> 
> Suggested:
> 
> ```
>         if (@available(iOS 11, *)) {
>             // Don't send an event for iOS 11 and up as userNotificationCenter will send the event for us, we don't want to duplicate them.
>         } else {
>             [_channel invokeMethod:@"Messaging#onMessage" arguments:notificationDict];
>         }
> 
>       completionHandler(UIBackgroundFetchResultNoData);
> ```
> 
> Other changes are fine.

Would you mind clarifying this a bit more e.g. where did find out that `userNotificationCenter` is only sending events for iOS 11 and above?

Thanks

**Comment by GKPK** [comment]
@Salakar May be this is helpful https://developer.apple.com/documentation/usernotifications/unusernotificationcenter

**Comment by GKPK** [comment]
@Salakar I guess it should be

if (@available(iOS 10, *)) {

**Comment by Salakar** [comment]
@GKPK I'm not sure your suggested change would be required then since `firebase_messaging` only supports 10.0 and above; https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/ios/firebase_messaging.podspec#L31

**Comment by GKPK** [comment]
@Salakar Yes, you are correct, thanks for the information, please ignore the suggested change and release a fixed version of plugin.

**Comment by GKPK** [comment]
Please approve this PR and release a fixed version asap, this is a production level app fix.

**Review by russellwheatley — COMMENTED** [review]
LGTM

**Comment by GKPK** [comment]
thank you @russellwheatley @Salakar

**Pull request merged**
