### PR TITLE
feat(android,*): upgrade Firebase Android SDK to 26.8.0

### LINKED ISSUE #4935: 🐛 [firebase_auth] No network method call exception has changed to 'firebase_auth/unknown' exception
## Bug report

**Describe the bug**
Whenever a Firebase Auth method that requires internet connection is invoked, the following exception is thrown:

```
Unhandled Exception: [firebase_auth/unknown] com.google.firebase.FirebaseException: An internal error has occurred. [ Unable to resolve host "www.googleapis.com":No address associated with hostname ]
```

From my testing, this has occurred with the following methods:
- `FirebaseAuth.createUserWithEmailAndPassword`
- `FirebaseAuth.signInWithEmailAndPassword`
- `FirebaseAuth.sendPasswordResetEmail`

### Steps to reproduce

1. Disable internet connection
2. Attempt to call `FirebaseAuth.signInWithEmailAndPassword`, `FirebaseAuth.createUserWithEmailAndPassword` or `FirebaseAuth.sendPasswordResetEmail`
4. Check the exception thrown

### Expected behavior

On the previous version `0.18.4+1`, the expected exception thrown was:

```
Unhandled Exception: [firebase_auth/network-request-failed] A network error (such as timeout, interrupted connection or unreachable host) has occurred.
```

---

## Additional context

This issue seems to have started on `firebase_auth 0.19.0` and above.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-PH)
    • Flutter version 1.22.6 at /usr/local/flutter
    • Framework revision 9b2d32b605 (11 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dominicorga/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke
        it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • POCOPHONE F1 (mobile) • 5992b5f5 • android-arm64 • Android 10 (API 29)

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.5
Flutter SDK 1.22.6
firebase_auth_test 1.0.0+1

dependencies:
- cupertino_icons 1.0.0
- firebase_auth 0.20.0+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

transitive dependencies:
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- firebase_auth_platform_interface 3.0.1 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+6 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- path 1.8.0-nullsafety.1
- plugin_platform_interface 1.0.3 [meta]
- quiver 2.1.4+1 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
```

</details>

---

### PR DESCRIPTION
**Pull request by NoamDev**
fixes #4935

## Description

Bump firebase BOM to 26.8.0. On current version no network errors are not reported correctly.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by NoamDev** [comment]
@Salakar thanks! Is there anyone specific that is worth requesting a review from?

**Review by Salakar — APPROVED** [review]

**Comment by Salakar** [comment]
> @Salakar thanks! Is there anyone specific that is worth requesting a review from?

Nope this is good to go. Most likely won't ship until Monday though most as this will cause all packages to get bumped

**Comment by NoamDev** [comment]
@Salakar Hi, do you think it's possible to make a release today?

**Comment by Salakar** [comment]
We're waiting on #6015 before we ship, hopefully today, latest tomorrow.

**Comment by NoamDev** [comment]
Oh, it seems it was published yesterday, but without firebase_core, so this PR wasn't released

**Pull request merged**
