### PR TITLE
[firebase_analytics_web] Add missing iOS files

### PR DESCRIPTION
**Pull request by tugorez**
## Description

We [tried to endorse](https://github.com/FirebaseExtended/flutterfire/pull/2794) this plugin as the web implementation of **firebase_analytics** but the integration tests failed due to missing ios files. This PR adds those missing files.

## Related Issues

flutter/flutter#45289

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by tugorez** [comment]
cc @ditman

**Comment by ditman** [comment]
Looks like there's a test failing in this package?

```
00:09 +4: /tmp/cirrus-ci-build/packages/firebase_analytics/firebase_analytics/test/observer_test.dart: FirebaseAnalyticsObserver handles only PlatformExceptions                                       
00:09 +4 -1: /tmp/cirrus-ci-build/packages/firebase_analytics/firebase_analytics/test/observer_test.dart: FirebaseAnalyticsObserver handles only PlatformExceptions [E]                                
  Invalid argument(s)
  package:mockito/src/mock.dart 342:7                       PostExpectation.thenThrow.<fn>
  package:mockito/src/mock.dart 119:45                      Mock.noSuchMethod
  package:firebase_analytics/firebase_analytics.dart 83:16  MockFirebaseAnalytics.setCurrentScreen
  package:firebase_analytics/observer.dart 80:17            FirebaseAnalyticsObserver._sendScreenView
  package:firebase_analytics/observer.dart 97:7             FirebaseAnalyticsObserver.didPush
  observer_test.dart 98:29                                  main.<fn>.<fn>.<fn>
  package:test_api                                          expect
  package:flutter_test/src/widget_tester.dart 369:3         expect
  observer_test.dart 98:7                                   main.<fn>.<fn>
  observer_test.dart 85:48                                  main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                _AsyncAwaitCompleter.completeError
  package:firebase_analytics/firebase_analytics.dart        MockFirebaseAnalytics.setCurrentScreen
  package:firebase_analytics/observer.dart 80:17            FirebaseAnalyticsObserver._sendScreenView
  package:firebase_analytics/observer.dart 97:7             FirebaseAnalyticsObserver.didPush
  observer_test.dart 98:29                                  main.<fn>.<fn>.<fn>
  package:test_api                                          expect
  package:flutter_test/src/widget_tester.dart 369:3         expect
  observer_test.dart 98:7                                   main.<fn>.<fn>
  observer_test.dart 85:48                                  main.<fn>.<fn>
  Expected: throws <Instance of 'ArgumentError'>
    Actual: <Closure: () => void>
     Which: returned <null>
  package:test_api                                   expect
  package:flutter_test/src/widget_tester.dart 369:3  expect
  observer_test.dart 98:7                            main.<fn>.<fn>
  observer_test.dart 85:48                           main.<fn>.<fn>
```

**Comment by ditman** [comment]
The failing test has been [disabled in `master`](https://github.com/FirebaseExtended/flutterfire/commit/2b220e5dbdcc3a72e6c0e86f0e00d961cdea2849). Can you rebase this and try again, please?

**Comment by tugorez** [comment]
Done @ditman. Everything looks great :)!

**Comment by ditman** [comment]
Published and tagged `firebase_analytics_web` version `0.1.1`

**Pull request merged**
