### PR TITLE
fix(cloud_firestore): Fixed crashes due to null `Settings`

### PR DESCRIPTION
**Pull request by sam-markoe**
## Description

With the recent migration to null safety, the migration allowed `Settings` to be nullable, and removed the default empty `Settings` in favor of null. Because of however the native interop translates these settings, instead of reading it from some config file it just fails and keeps everything null. 

Since settings are no longer defined, the app will crash on any sort of gRPC call because the Firestore `host` setting isn't defined.

This change ensures the `Settings` object is defined.

## Related Issues

Fixes FirebaseExtended/flutterfire#4948

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
  - Unit tests seem to be already broken. I believe affected tests are still fine!
- [X] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
  - Analyzer already has unrelated issues.
- [X] I read and followed the [Flutter Style Guide].
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

It's a breaking change in the sense that you can't set `Settings` to `null` anymore, but that made it so your app was broken. In that case, bumping the version makes little sense.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by russellwheatley — APPROVED** [review]
Tested on Android & Web. Provided it passes tests once pending CI fixes are merged; This LGTM.

**Comment by russellwheatley** [comment]
@googlebot I fixed it.

**Comment by russellwheatley** [comment]
@googlebot I fixed it.

**Comment by russellwheatley** [comment]
@googlebot I fixed it.

**Comment by russellwheatley** [comment]
@googlebot I fixed it.

**Review by Salakar — APPROVED** [review]

**Comment by Salakar** [comment]
Note: Ignoring CLA status on this one as I've confirmed they are setup for @russellwheatley, additionally Invertase has an organisation/employer CLA signed - which also covers this.

**Pull request merged**
