### PR TITLE
[firebase_database]: Fix for ClassCastException in issue #81

### PR DESCRIPTION
**Pull request by jpeiffer**
## Description

* Pretty simple fix for the casting issue documented in https://github.com/FirebaseExtended/flutterfire/issues/81

## Related Issues

* https://github.com/FirebaseExtended/flutterfire/issues/81

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by jpeiffer** [comment]
Replaced with PR: https://github.com/FirebaseExtended/flutterfire/pull/1708

**Comment by jpeiffer** [comment]
Ooops, accidentally closed this one when I meant to close another.

**Comment by mclark4386** [comment]
This is still an issue on android. Any chance this fix could get merged?^^;

**Comment by GrahamDi** [comment]
@jpeiffer Hi, as per @mclark4386, is there an ETA for this to be merged?

**Comment by jpeiffer** [comment]
Outside of my control, unfortunately.  This is the 2nd time I created a PR to fix the issue, and it's been ignored both times with basically no feedback as to why.  :(

**Comment by tanwarsatya** [comment]
why is this not merged till now, this is a show stopper and not allowing to use firebase database from flutter

**Comment by Ehesp** [comment]
Thanks for this PR. It can now be closed as it's been addressed in 3.1.5 release, with tests.

**Pull request closed without merging**
