### PR TITLE
[firebase_database] Fix for cacheSize issue

### PR DESCRIPTION
**Pull request by jpeiffer**
## Description

* Pretty simple fix for the casting issue documented in #81 

## Related Issues

#81 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [X] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [X] All existing and new tests are passing.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [X] I read and followed the [Flutter Style Guide].
- [X] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [] I updated CHANGELOG.md to add a description of the change.
- [X] I signed the [CLA].
- [X] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by jpeiffer** [comment]
It looks like the failures were CI/CD side and not code related as they both resolved with a timeout error.

If there's something I need to do with the code, please let me know.

**Comment by dvird-ironsource** [comment]
???

**Comment by dvird** [comment]
???

**Comment by Ehesp** [comment]
Thanks for this PR. It can now be closed as it's been addressed in 3.1.5 release, with tests.

**Pull request closed without merging**
