### PR TITLE
feat: introduce FirebaseException StackTrace support

### PR DESCRIPTION
**Pull request by Ehesp**
## Description

Currently whenever a `FirebaseException` is thrown, any stack traces provided with a genuine error are lost. This PR adds support for an optional stack trace, along with updating the current reworked plugins to forward the trace on.

Example:

image

## Related Issues

N/A

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

### CODE REVIEW

**Comment by Ehesp** [comment]
Note this moves changes to an "unpublished" state; no version bumps or change log version changes.

**Comment by HofmannZ** [comment]
Would be nice if this could be reappears alongside Crashlytics, @Ehesp what do you think?

**Comment by Ehesp** [comment]
Waiting on https://github.com/FirebaseExtended/flutterfire/pull/3700 to land for this one

**Comment by Salakar** [comment]
Closing for now given how far behind it is.

**Pull request closed without merging**
