### PR TITLE
feat(web): bump all firebase-js-sdk versions to current stable

### PR DESCRIPTION
**Pull request by mikehardy**
## Description

Please note this is speculative! Do not merge until verifying the related issues are resolved.

To be clear: there are reported issues with current stable firebase-js-sdk, this PR is by request from @Ehesp to see if there are any other issues that show up in CI on top of the already reported issues.

## Related Issues

#5096 - auth.useEmulator *requires* 8.0.1 of firebase-js-sdk or better, so this or similar is required for it
#4127 - firestore collection ref get- NoSuchMethodError: invalid member on null: 'includeMetadataChanges'

There may be others, these are the ones I'm aware of.
CI may surface new issues as well and should be examined closely

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- **it is unknown if it is a breaking change, I don't *think* so** [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by mikehardy** [comment]
Firestore web fails as expected (this is a positive sign: E2E CI should confirm known issues)

Firestore android fails for something that must be unrelated since nothing was changed about android:

```

------------------------------
|        Test Failures       |
------------------------------

1) putData > uploads a file with buffer
   [E]: [firebase_storage/unauthorized] User is not authorized to perform the desired action.
          ├─  dart:async                                                                                          new Future.error
          ├─  package:firebase_storage_platform_interface/src/method_channel/utils/exception.dart:27:19           catchFuturePlatformException
          ├─  package:firebase_storage_platform_interface/src/method_channel/method_channel_task.dart:83:9        new MethodChannelTask.<fn>
          ├─  dart:async                                                                                          _StreamImpl.listen
          ├─  package:firebase_storage_platform_interface/src/method_channel/method_channel_task.dart:53:29       new MethodChannelTask
          ├─  package:firebase_storage_platform_interface/src/method_channel/method_channel_task.dart:271:9       new MethodChannelPutTask
          ├─  package:firebase_storage_platform_interface/src/method_channel/method_channel_reference.dart:154:12 MethodChannelReference.putData
          ├─  package:firebase_storage/src/reference.dart:111:44                                                  Reference.putData
          ├─  test_driver/reference_e2e.dart:215:49                                                               runReferenceTests.<fn>.<fn>.<fn>
          ├─  test_driver/reference_e2e.dart:209:42                                                               runReferenceTests.<fn>.<fn>.<fn>
```

**Comment by russellwheatley** [comment]
I think @Ehesp might have thoughts on this PR. I have a vague memory of something blocking Firebase JS version bumps which I'm blanking on.

**Comment by Ehesp** [comment]
Just as a side note while passing by, this would need updating: https://github.com/FirebaseExtended/flutterfire/blob/master/docs/versions.js#L42

**Comment by mikehardy** [comment]
@russellwheatley yes absolutely need a look here (from @Ehesp as tagged above) because of #4127

**Comment by mikehardy** [comment]
I did not know that versions file existed :-), I made the edit there and re-pushed

**Comment by russellwheatley** [comment]
@mikehardy Yeah, I deleted that comment immediately once I noticed you'd tagged Elliot, but I guess you still got the notification 😄 .

 Firestore web test was failing so I've reran 🤞 .

**Comment by mikehardy** [comment]
@russellwheatley firestore_web will not work until there is a fix for #4127 per PR description above:

> #4127 - firestore collection ref get- NoSuchMethodError: invalid member on null: 'includeMetadataChanges'

And https://github.com/FirebaseExtended/flutterfire/pull/5170#issuecomment-787451876

**Comment by Levi-Lesches** [comment]
I saw your comment on #4127, does `firebase_auth` need `8.0.1` or higher than that? In any case, it seems like something official has to be done with #4127, but I'm not sure exactly what's causing the issue.

**Comment by mikehardy** [comment]
@Levi-Lesches I thought because of the commit messages on firebase-js-sdk regarding making the auth.useEmulator API public that it needed a quite recent version - 8.2.4 I think - but we had a success report for auth.useEmulator on 8.0.1. So current collective wisdom is that firebase-js-sdk 8.0.1 is the sweet spot of "has auth.useEmulator" and "firestore_web still works", if that is what you are asking

**Comment by Levi-Lesches** [comment]
Okay, so pulling from https://github.com/FirebaseExtended/flutterfire/issues/4127#issuecomment-754171740: 
> I wanted the emulators only available in >8.0.0 (i.e. auth and firestore), and the below configuration finally worked for me.
>
> ```HTML
> <script src="https://www.gstatic.com/firebasejs/8.2.1/firebase-app.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.2.1/firebase-analytics.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.2.1/firebase-auth.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.0.1/firebase-firestore.js"></script>

Have you tried this configuration?

**Comment by mikehardy** [comment]
I have not, I focus almost exclusively on "latest version of everything" and specifically so when doing auth.useEmulator feature PR, so my experience is rarely useful for real-world experience unfortunately. But, I'm glad you have auth.useEmulator working and I hope you enjoy it :-), it made a big difference for us in CI on other projects as we no longer hit auth limits all the time, so it de-flaked our CI E2E tests a lot.

**Comment by Levi-Lesches** [comment]
Ah, so I guess this PR is waiting for the latest versions of `cloud_firestore` and `firebase_auth` to support the latest JS versions? I think #5050 might hold that up, it seems there are some null-safety issues in the latest versions.

**Comment by Salakar** [comment]
Looks like we might be unblocked now, have updated base branch to re-trigger CI 🤞

**Comment by mikehardy** [comment]
Looks like a timeout and unexpected auth module issue on apple but web flew through! So I think the PR is okay

Looks like we are on 8.4.0 now though? https://firebase.google.com/support/release-notes/js (with a mention of 8.4.1 on the actual README.md of the repo)

Maybe one last bump to current-current before merge?

**Comment by Ehesp** [comment]
FYI I'm not sure whether https://github.com/firebase/firebase-js-sdk/issues/4145 impacts this release. It's a blocker from upgrading but from the looks of it is a Firebase issue, although I'd like to confirm.

**Comment by mikehardy** [comment]
Superceded by #4464 - it's all done on main dev branch now :rocket:

**Pull request closed without merging**
