### PR TITLE
Create firebaseopensource.com configuration

### PR DESCRIPTION
**Pull request by samtstern**
## Description

I just copied the one from flutter/plugins and changed the `content` key to point at README.md*

## Related Issues

N/A

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [ x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x ] All existing and new tests are passing.
- [x ] I updated/added relevant documentation (doc comments with `///`).
- [ x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [ x] I read and followed the [Flutter Style Guide].
- [ x] The title of the PR starts with the name of the plugin surrounded by square brackets, e.g. [shared_preferences]
- [ x] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ x] I updated CHANGELOG.md to add a description of the change.
- [ x] I signed the [CLA].
- [ x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by samtstern** [comment]
Follow ups that this enabled:
https://github.com/firebase/firebaseopensource.com/commit/368a84cf077e7d194b99cb4cc90b3af571a5209d
https://github.com/firebase/firebaseopensource.com/commit/99e62089444c3c0c93b8210c362decd9a35a081f

**Comment by collinjackson** [comment]
Seems like the old plugins repository description is still on firebaseopensource.com:

Screen Shot 2019-09-10 at 09 42 29

**Comment by kroikie** [comment]
@samtstern Where is that text generated?

**Comment by samtstern** [comment]
I am redeploying the site now to fix that.

**Comment by samtstern** [comment]
Also see:
https://github.com/flutter/plugins/pull/2055

**Comment by samtstern** [comment]
New page is now live:
https://firebaseopensource.com/projects/firebaseextended/flutterfire/

Old page is still live but blacklisted from appearing on the homepage.

**Pull request merged**
